"""CPU阶段报告：AI记录、实际条件合同、失败定位和多视角GPU输入，不要求旧数据重审。"""
from pathlib import Path
import argparse,json,shutil,html

def read(p):return json.loads(Path(p).read_text())
def e(v):return html.escape(str(v))
def main(root,old):
    out=root/'review';out.mkdir(exist_ok=True);(out/'assets').mkdir(exist_ok=True);(out/'raw').mkdir(exist_ok=True)
    summary=read(root/'ai_review_summary.json');admission=read(root/'training_admission.json');contract=read(root/'driveeditor_contract_validation.json');queue=read(root/'gpu_queue.json');mv=read(root/'multiview/full_track_catalog.json');audit=read(root/'training_input_audit.json')
    reviews={r['case_id']:r for r in read(root/'ai_case_reviews.json')['reviews']}
    for p in (root/'raw').glob('*.csv'):shutil.copy2(p,out/'raw'/p.name)
    for filename,dest in [('evidence/S045_f28_trace.png','S045_source.png'),('multiview/selected_contacts.jpg','multiview.jpg'),('multiview/selected_contacts_geometry_only.jpg','multiview_geometry_only.jpg')]:shutil.copy2(root/filename,out/'assets'/dest)
    for key in ['input','condition','gt']:shutil.copy2(old/'synthetic_delivery/assets/W029'/f'008_{key}.jpg',out/'assets'/f'W029_{key}.jpg')
    statuses={'reject':'训练输入拒绝','uncertain':'训练输入待定','train_usable_pending_human':'技术可用，待人工全检','ai_2_unverified':'原AI 2分，未认证','hold_user_reported_silhouette':'用户指出轮廓疑点，暂缓'}
    table=''.join(f'<tr><td>{e(r["case_id"])}</td><td>{r["original_ai_score"]}</td><td>{e(statuses[r["training_admission"]])}</td><td>{e(r["donor_source_id"])}</td><td>{e((r.get("visual_reassessment") or {}).get("reason",reviews[r["case_id"]]["failure_type"]))}</td></tr>' for r in admission['cases'])
    rc=admission['reassessed_counts'];usable=[r['case_id'] for r in admission['cases'] if r['training_admission']=='train_usable_pending_human']
    rawlinks=' · '.join(f'<a href="raw/{e(p.name)}">{e(p.name)}</a>' for p in (out/'raw').glob('*.csv'))
    groups={}
    for r in queue['jobs']:groups.setdefault(r['instance_token'],[]).append(r)
    views=''.join('<li>'+e(','.join(rs[0]['source_ids']))+'：'+e(' / '.join(r['camera'] for r in rs))+'；'+e(' / '.join(f"yaw {r['view_angles_deg'][0]:.1f}°" for r in rs))+'</li>' for rs in groups.values())
    svg='''<svg viewBox="0 0 1120 190" role="img" aria-label="真实Y作监督，X经mask清零再作DriveEditor条件"><defs><marker id="a" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8" fill="#88cfff"/></marker></defs><g fill="#203953" stroke="#597995"><rect x="10" y="20" width="160" height="56" rx="6"/><rect x="220" y="20" width="185" height="56" rx="6"/><rect x="455" y="20" width="190" height="56" rx="6"/><rect x="700" y="20" width="185" height="56" rx="6"/><rect x="940" y="20" width="165" height="56" rx="6"/><rect x="455" y="120" width="190" height="56" rx="6"/></g><g fill="#eff7ff" font-size="17" text-anchor="middle"><text x="90" y="53">真实多视角 A</text><text x="312" y="53">清洁 mask / 固定轨迹</text><text x="550" y="53">X + 删除洞 H</text><text x="792" y="53">洞内清零 masked-X</text><text x="1022" y="53">DriveEditor 条件</text><text x="550" y="153">真实 Y → 监督目标</text></g><g fill="none" stroke="#88cfff" stroke-width="2" marker-end="url(#a)"><path d="M171 48H216"/><path d="M407 48H451"/><path d="M647 48H696"/><path d="M887 48H936"/><path d="M647 148H1022V80"/></g></svg>'''
    text=f'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>V77 r2 · 造数入口修订</title><style>body{{background:#101823;color:#e9eff7;font:16px/1.7 system-ui;margin:0}}main{{max-width:1200px;margin:auto;padding:28px}}h1{{font-size:29px}}h2{{font-size:22px}}section{{background:#182536;border:1px solid #34465d;border-radius:10px;padding:20px;margin:20px 0}}a{{color:#91ceff}}img,svg{{max-width:100%;height:auto}}.row{{display:grid;grid-template-columns:1fr 1fr;gap:15px}}figure{{margin:0}}figcaption,.muted{{color:#b4c5db;font-size:14px}}table{{border-collapse:collapse;width:100%;font-size:14px}}td,th{{padding:9px;border-bottom:1px solid #3c5065;text-align:left}}.warning{{border-left:4px solid #e6a668;padding-left:14px}}code{{color:#b8d8ff}}@media(max-width:700px){{.row{{grid-template-columns:1fr}}}}</style><main>
<h1>Target + Protected Actors · r2 CPU 修订</h1><p>2026-09-30 · 按用户最新五项训练输入标准，重新检查37个原AI 1分例；原始评分不改写。<b>没有新合成视频、没有GPU推理、没有训练。</b>下一步停在冻结SAM2的小批量多视角预检。</p>
<section><h2>DriveEditor 到底看到什么</h2>{svg}<p><b>在本轮沿用的官方 background/deletion 合同下，模型看不到完整 synthetic-X。</b>RGB 条件先按 H 清零，再编码；首帧 CLIP 场景条件也来自已经清零的图。监督 <code>jpg</code> 是真实 Y，扩散训练对它的 latent 加噪。去删车的外观、3D深度条件是官方 blank/deletion 的空占位。</p><p>已执行官方 <code>get_blank()</code> 未修改方法的 CPU 张量测试，并核对 26 个字段的键/形状。改变洞内 X，条件不变；改变隐藏 Y，仅监督改变；真实 D008 的10帧满足 masked-X = masked-Y。没有执行 VAE/UNet 前向或反向。</p><p class="warning">因此，完全被 mask 盖住的贴片，其颜色、光照、边缘美化不能直接改善这条训练条件。优先修 <b>洞的位置/形状、被遮住的真实 B/C、剩余可见证据、时间和多视角几何</b>。若未来让网络看完整 X，需明确改已有条件的数据语义并重新做对照；本轮没有偷偷切换。</p><p><a href="https://github.com/yvanliang/DriveEditor/blob/main/sgm/data/nus.py">官方训练loader</a> · <a href="https://github.com/yvanliang/DriveEditor/blob/main/sgm/models/diffusion.py">训练目标编码</a></p></section>
<section><h2>你指出的右下角贴片</h2><p>定位：<b>W029 / 第8帧（从0开始） → S045 / 原第28帧</b>。AI打2分；用户明确拒绝。原车下缘紧贴可见自车机盖，右下方轮胎/暗部/路面难以分开，旧SAM2把不可靠下缘随车复制。不能靠最大连通域、固定模糊或直接裁轮胎来宣布修好。</p><div class="row"><figure><img src="assets/W029_input.jpg"><figcaption>旧合成X：右下块随车一起被贴入，属于失败证据。</figcaption></figure><figure><img src="assets/W029_condition.jpg"><figcaption>同帧masked-X：贴片被盖住；脏轮廓仍会影响删除洞的形状。</figcaption></figure></div><figure><img src="assets/S045_source.png"><figcaption>同一真实供体：原RGB / SAM2 overlay / 隔离像素。旧图仅作定位，不要求再打分。</figcaption></figure><p>S045旧来源禁用，20个衍生case均禁止继续复用。新增供体入口规则已接入提案和渲染两处：机盖/底边近邻、空mask、明显多分量污染风险先挡住；原mask原样留存，不自动裁剪后放行。</p></section>
<section><h2>从外观打分改为训练输入检查</h2><p>原49例、810帧已与文件逐项对账。原AI分数为37例1分、11例2分、1例0分，原始四份文件：{rawlinks}。最新指令已覆盖此前“低分全部淘汰、不重审”的规则。</p><p><b>一个gpt-6-sol / xhigh / 非fast subagent实际检查全部37个1分例的首/中/末帧</b>，主线程全帧核验630帧。新结论：<b>{e(rc)}</b>。可用候选：{e('、'.join(usable))}。<code>train_usable_pending_human</code>表示五项技术检查下可用，仍待原定人工全检；不是自动开始训练。</p><p>五项标准：车辆状洞、合理尺度/位置、时间连续、A在B前、最终条件无合成残留。外观、受光、硬边不单独否决；真实空间悬浮、压ego、异常洞形和误遮保护车仍不通过。D006被真实机盖覆盖证据拒绝；D009按用户明确空间失败保持0分。其他原2分例不凭分数认证。</p><p class="warning">630帧RGB漏出为0。nearest缩小到1/8的mask再放大，会有边界cell未被标洞；但车像素在VAE/CLIP之前已按全分辨率H清零，所以这不等同合成RGB泄漏。已量化max-pool整cell覆盖候选及其额外保护区影响，未悄悄替换官方mask规则，也未声称跑过VAE/UNet。</p><p>CSV的每例帧评分均为常数，不证明逐帧实际看过。Sol抽帧和工程全帧检查分别记录，人工全检仍未回传。</p><details open><summary>全部49例：旧分数与新训练判断</summary><table><thead><tr><th>Case</th><th>原AI分</th><th>当前训练状态</th><th>供体</th><th>新判断 / 原备注</th></tr></thead><tbody>{table}</tbody></table></details></section>
<section><h2>新多视角素材与GPU停止点</h2><p>原短窗45个实例中没有足够清晰的跨相机组合。沿同一真实实例扩大到完整track后，发现8个跨相机实例。第一版仅追求角度跨度的9图提案中，真实RGB仍有小目标/前车遮挡，因此没有推理；保存为对照。修订为目标至少128×72px、优先较弱视角仍清楚、保守排除前方GT包络交叠与底边邻近。</p><p>修订后选出 <b>{len(groups)} 个真实实例 / {len(queue['jobs'])} 个视角</b>，RGB已齐。每个实例保持同一nuScenes instance token与真实相机/曝光。相机曝光异步，不称为同步瞬时多目；不是翻转图或生成补全视角。几何筛选不等于分割合格。</p><ul>{views}</ul><img src="assets/multiview.jpg"><p>下一步只执行这{len(queue['jobs'])}张的现有SAM2分割，检查像素清洁度；通过后才扩成连续窗口。整段固定选择同一供体camera-track；无真实合适视角则拒绝，不逐帧换图。此处尚未得到新的连续多视角合成视频，也没有达到约50例合格数据。</p><details><summary>查看被改进的第一版几何提案</summary><img src="assets/multiview_geometry_only.jpg"><p>这些图不作为合格样本，不启动额外旧例复审。</p></details></section>
<section><h2>预算与范围</h2><p>先用确定性CPU检查挡掉坏来源，按同一供体复用结果；只启动一个Sol xhigh、非fast subagent，按用户最新授权完成这一次37例重评。后续不重复已完成评审，只查新造/实际修正的样本。未下载新模型、未启动训练、定时任务或电源操作。当前无卡资源0.5 CPU / 2GiB，使用流式元数据读取与低内存合同验证；数据盘约145GiB空闲。</p><p>有根据场景修正光照/阴影的模型，例如<a href="https://github.com/NVIDIA/harmonizer">NVIDIA Harmonizer</a>，但当前完全遮挡合同会隐藏贴片外观。本阶段优先让洞和真实被遮内容正确，不引入额外外观生成网络。</p><p class="muted">7项准入/视角单测、实际渲染入口阻断、官方CPU合同与630帧条件检查通过；浏览器交互未实测。历史视频/评分/配置均保留。task/run: WS-V77-TARGET-PROTECTED-20260929/r2；failure: V77-F02。</p></section></main></html>'''
    text=text.replace('DriveEditor 条件</text>','DriveEditor</text>').replace('S045旧来源禁用，20个衍生case均禁止继续复用。','S045旧贴片来源暂不继续造新数据；其20个历史派生样本按各自实际H与空间证据判断训练可用性，不因车身RGB污染一概否决。').replace('AI打2分；用户明确拒绝。','AI打2分；用户明确指出贴片问题，新训练判据下暂缓。').replace('<h2>从外观打分改为训练输入检查</h2>','<h2>从外观打分改为训练输入检查</h2><p><a href="data_review.html">打开37例四列视频与逐帧审核页</a>：新判据、新评分存储，复用原视频。</p>')
    (out/'index.html').write_text(text,encoding='utf-8');report={'task_id':'WS-V77-TARGET-PROTECTED-20260929','run_id':'r2','ai_scores':summary['case_score_counts'],'training_reassessment_counts':rc,'old_cases_re_reviewed_under_new_contract':37,'new_gpu_forwards':0,'new_training_steps':0,'gpu_queue_views':len(queue['jobs']),'gpu_queue_instances':len(groups),'human_full_frame_review_received':False,'training_ready':0,'state':'CPU_complete_awaiting_user_GPU','full_X_seen':False,'new_synthetic_cases':0,'independent_subagent_calls_this_run':1}
    (root/'summary.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');print(json.dumps(report,ensure_ascii=False,indent=2))

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--root',type=Path,required=True);p.add_argument('--old',type=Path,required=True);a=p.parse_args();main(a.root,a.old)
