from pathlib import Path
import argparse,json,shutil
p=argparse.ArgumentParser();p.add_argument('--work-root',type=Path,default=Path.cwd()/'work')
B=p.parse_args().work_root.resolve();O=B.parent/'outputs'/'v77-actor-audit';D=json.loads((O/'review_data.json').read_text(encoding='utf-8'))
sections=[]
for s in D['scenes']:
    n=s['name'];hard=n=='scene_0230';actor=s['actor_id'];audit=json.loads((O/n/'command_audit.json').read_text(encoding='utf-8'))
    title='路边棕色旅行车 / 两厢车' if hard else '停车场银白色 SUV'
    status='旧 MOVE 未通过：50 / 50 帧与 actor 2 框相交' if hard else '旧 MOVE 未准入：100 帧无框相交，但最窄只有 8.4 cm'
    command='后移 1.70 m + 向车身右侧移 1.06 m' if hard else '前移 1.90 m + 向车身左侧移 0.63 m'
    explanation=('你对前后空间的担心有依据。目标是 actor 22，前方是 actor 14，后方是 actor 2。旧位移终点与整段平移扫掠区域，都在全部 50 帧中碰到 actor 2 的 GT 框。另查纯车头方向：前移 2 m 会碰 actor 14，后移 2 m 会碰 actor 2，均为 50 / 50 帧。' if hard else '目标是 actor 25，靠近它的邻车为 actor 52。对 0–99 帧检查时，旧位移的终点和扫掠体均未与已标注同高度 actor 框相交，但 f077（7.7 s）距离 actor 52 仅 0.0839 m。这个余量不足以吸收框误差，也没有验证路缘、草地、围栏或可行驶区。')
    direction=('同一个 GLB、相同材质、相同 GT 位姿，仅比较局部 yaw 0° 与 180°。中间旧朝向把前脸放在了原车尾部；右侧转正后车身轮廓与棕色外观明显更接近原图。这是接入时的车头方向错误，不能据旧图断言资产变成另一辆车。' if hard else '同一个 GLB 比较 yaw 0° 与 180°，原来的 0° 车头方向正确。因此没有对这个资产统一翻转。生成贴图偏亮、前景杆和车身边缘的合成仍不自然，单凭这些图不能拆出材质、光照、遮挡各自的贡献。')
    scale=('长 / 宽 / 高缩放约为 2.268 / 2.182 / 2.269，差异较小。这里仍放入统一缩放控制，防止把放置形变归给原始 GLB。' if hard else '旧长 / 宽 / 高缩放约为 2.502 / 2.314 / 2.892。相比按车长统一缩放，车高被额外拉伸约 15.6%，宽度缩小约 7.5%。右侧统一缩放保留 GLB 比例，并把底面锚在同一 GT 框底部；它是形变诊断，不等于确认了真实尺寸。')
    cards=''.join(f'<article><h4>{label}</h4><p>{note}</p><video controls playsinline preload="metadata" src="{n}/{key}.mp4" poster="{n}/{key}_poster.jpg"></video></article>' for key,label,note in [
       ('raw','① 原视频：明确目标','青色轮廓为本次 SAM2 目标；右侧放大同一区域。'),
       ('corrected','② 同 GLB：修正放置后的原位','修正相机投影与已确认的车头方向；仍采用原逐轴尺寸匹配。'),
       ('delete','③ DELETE：独立检查补景','只看 ProPainter 的去车背景；此栏没有 GLB，也没有执行 MOVE。')])
    sections.append(f'''<section id="{n}" data-scene="{n}"><div class="sectiontitle"><div><span class="kicker">{n} · actor {actor}</span><h2>{title}</h2></div><a class="button" href="../v77-explicit-poc/{n}/actor.glb" download>原始 GLB（未改网格）</a></div>
<div class="alert {'red' if hard else 'amber'}"><strong>{status}</strong></div>
<p>这次操作绑定的是下面青色标出的车。粉色箭头表示<strong>旧 2 m 指令的车中心投影方向</strong>，不代表它合法；右侧是原图裁剪。GT track：<code>{audit['track_id']}</code>，尺寸（长×宽×高）：{' × '.join(f'{x:.3f}' for x in audit['size_lwh'])} m。</p>
<a href="{n}/target.jpg"><img class="wide" src="{n}/target.jpg" alt="原图中的目标 actor {actor} 与放大图"></a>
<div class="split"><a href="{n}/bev.jpg"><img src="{n}/bev.jpg" alt="旧 MOVE 扫掠与邻车 GT 框俯视检查"></a><div><h3>旧指令实际移动到哪里？</h3><p><strong>{command}</strong>（参考帧车身坐标）。原代码从参考相机“屏幕向右”取方向，并未按车头、停车位或邻车空间来选指令。</p><p>{explanation}</p><p>俯视图将车头朝上显示。青框为原位置，红框为终点，橙色为整个平移过程经过的区域；检查覆盖完整的 {'50 帧 / 4.9 s' if hard else '100 帧 / 9.9 s'}，不是只抽看 10 帧。</p><p class="muted">检查对象是 GT 有向框在地面的投影，按高度过滤；这是保守的对象间几何筛查。未包含静态设施、ego 车身、道路规则，也不是带时间和转向约束的可驾驶轨迹。</p><a href="{n}/command_audit.json">完整逐帧几何证据 JSON</a></div></div>
<h3>先核对车头，再判断资产</h3><p>{direction}</p><a href="{n}/yaw_control.jpg"><img class="wide" src="{n}/yaw_control.jpg" alt="原车、相同 GLB 朝向零度和一百八十度的对照"></a>
<h3>分开看 GLB 比例与放置缩放</h3><p>{scale}</p><a href="{n}/scale_control.jpg"><img class="wide" src="{n}/scale_control.jpg" alt="原车、逐轴缩放、保留比例统一缩放对照"></a>
<h3>10 个时间点：目标、修正原位、独立 DELETE</h3><p>每栏内部：左为当前相机全图，右为同一目标窗口放大。{'相机随目标可见性切换 CAM2 → CAM4 → CAM5；切换已写在视频画面中。' if hard else '全部采用 CAM3；杆、围栏与其他前景遮挡仍应关注。'} 这是抽样时序检查（{'2 fps、源时刻 0–4.5 s' if hard else '1 fps、源时刻 0–9 s'}），不是完整 10 Hz 重渲染。原位 GLB 是外部 Blender 合成，不是 Ω 官方 factual 接口。</p>
<div class="controls"><button class="play">三栏同步播放</button><button class="pause">暂停</button><input aria-label="时间点" class="scrub" type="range" min="0" max="9" value="0"><output></output></div><div class="videos">{cards}</div>
<p class="muted">旧 MOVE 已从主审核对比中撤下；未把任何新方向冒称为已合法。修正原位仍缺场景深度遮挡、投影阴影和照度匹配，不能直接当高保真结果。<a href="../v77-explicit-poc/index_pre_audit.html#{n}">查看带旧结论的历史页（已撤回，仅留证）</a></p></section>''')
head='''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>v77 目标与 MOVE 指令审计</title><style>
:root{font-family:"Microsoft YaHei",system-ui,sans-serif;color:#21374a;background:#edf2f6;line-height:1.72}*{box-sizing:border-box}body{margin:0}header{background:#112d41;color:#fff;padding:44px max(24px,calc((100vw - 1450px)/2))}h1{font-size:38px;margin:8px 0 14px;line-height:1.35}h2{font-size:27px;margin:5px 0}h3{font-size:22px;margin:28px 0 8px}h4{margin:0;font-size:17px}.kicker{font-size:13px;letter-spacing:.09em;color:#4b9c96;font-weight:750}header .kicker{color:#7be6d3}header p{max-width:1120px;color:#d3e2ee}nav{display:flex;gap:12px;flex-wrap:wrap}a{color:#08796f}header a{color:#affbe4}.button,button{display:inline-block;padding:8px 13px;border:1px solid #568985;border-radius:8px;background:transparent;color:#086d64;font-weight:700;cursor:pointer;text-decoration:none}main{max-width:1498px;margin:auto;padding:24px}section{background:white;border:1px solid #d3e0e7;border-radius:15px;padding:26px;margin:28px 0 44px;scroll-margin-top:15px}.sectiontitle{display:flex;justify-content:space-between;align-items:center;gap:20px}p{margin:12px 0}code{font-size:13px;overflow-wrap:anywhere}.alert{padding:16px 19px;border-radius:8px;border-left:5px solid;margin:20px 0}.red{background:#fff0f2;border-color:#ca4565}.amber{background:#fff5e7;border-color:#c89135}.green{background:#e9f6f2;border-color:#298978}.wide{width:100%;height:auto;border-radius:9px;display:block}.split{display:grid;grid-template-columns:minmax(320px,520px) 1fr;gap:30px;margin-top:24px}.split img{width:100%;height:auto}.muted{color:#607688;font-size:14px}.videos{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.videos article{border:1px solid #c5d8df;border-radius:10px;overflow:hidden;background:#f5f9fb}.videos h4,.videos p{padding:0 13px}.videos h4{padding-top:12px}.videos p{font-size:13px;min-height:45px;margin:5px 0 12px}video{display:block;width:100%;background:#132c40}video:fullscreen{object-fit:contain}.controls{display:flex;gap:12px;flex-wrap:wrap;align-items:center;margin:16px 0}.controls input{width:220px}.controls output{font-size:14px;color:#0b776d}.flow{display:flex;gap:8px;align-items:center;flex-wrap:wrap;padding:18px 0}.flow span{padding:10px 14px;border:1px solid #a9c7cd;border-radius:8px;background:#f7fbfc}.flow b{color:#23887b}table{width:100%;border-collapse:collapse;margin:18px 0}td,th{border:1px solid #d1dee5;padding:12px;text-align:left;vertical-align:top}th{background:#e9f2f5}footer{color:#697f90;font-size:13px;padding:5px 0 25px}@media(max-width:980px){.videos{grid-template-columns:1fr}.split{grid-template-columns:1fr}.split img{max-width:600px}.sectiontitle{display:block}h1{font-size:29px}section{padding:18px}main{padding:12px}}
</style></head><body><header><span class="kicker">WS-V77-ACTOR-COMMAND-AUDIT-20260926 / r1</span><h1>先把目标与指令查清楚，再评价重建资产</h1><p>本轮审计确认：第一例的旧 MOVE 会与邻车 GT 框相交，且车头在合成时放反；第二例仅有约 8.4 cm 的最小框间距，还存在相机投影与缩放问题。此前把合成差异直接归为“GLB 失败”、据此关闭这条路线的结论过早，现撤回。原始资产、旧视频与完整实验保留。</p><nav><a href="#scene_0230">actor 22：哪辆车、撞哪里</a><a href="#scene_0255">actor 25：间距与缩放</a><a href="#findings">结论与证据边界</a></nav></header><main>
<div class="alert green"><strong>本页没有训练或重新生成资产。</strong>复用原两个 GLB，检查完整 GT 轨迹；增加同资产朝向、相机和比例控制。用户反馈“本地 Blender 的 GLB 看起来没太大问题”被保留为形状复核意见，人工通过字段仍为空。</div>
<div class="flow" aria-label="architecture components"><span>原 RGB + GT track / camera</span><b>→</b><span>目标标注 + 全时窗扫掠检查</span><b>→</b><span>指令可用性</span><br><span>原 GLB + 同一背景</span><b>→</b><span>朝向 / 投影 / 缩放控制</span><b>→</b><span>可归因的人眼审核</span></div>
'''
tail='''<section id="findings"><h2>这次修正了什么结论</h2><table><tr><th>问题</th><th>查到的证据与处理</th></tr><tr><td>目标不清楚</td><td>原页只给 actor ID 与六相机小图；现在提供目标 SAM2 轮廓、原车裁剪、GT track、尺寸与逐时刻放大视频。</td></tr><tr><td>MOVE 的有效性</td><td>scene_0230 旧 MOVE 与 actor 2 框相交 50/50；纯前移/后移 2 m 也分别与 actor 14/2 相交。scene_0255 旧 MOVE 无框相交，但最窄 8.4 cm，未完成静态环境审查。两条旧 MOVE 均不能作为合法编辑验收用例。</td></tr><tr><td>车头与相机</td><td>scene_0230 增加局部 yaw 180°校正，scene_0255 保持 0°；修复 Blender 主点 shift 的归一化与图像缩放像素中心。两参考视图的旧数学投影偏差分别为 0.98 px、5.99 px。新 20 视图 × 9 射线检查均小于 0.02 px；这仅验证坐标实现，不代表重建误差如此小。</td></tr><tr><td>GLB 本体</td><td>结构完整性与合成质量分开评估。第二例旧逐轴缩放相对按长度统一缩放把高度拉高 15.6%。撤回“资产失败 / 关闭路线”的旧归因，保留材质、光照、细节一致性待审；没有反向宣布高保真通过。</td></tr><tr><td>仍成立的观测</td><td>无 GLB 的 ProPainter DELETE 中仍可见暗斑或车形残影；这与车头放反、相机误差独立。当前覆盖合成缺深度遮挡、阴影、照度匹配；这些限制需独立处理。</td></tr></table>
<h3>后续 MOVE 的准入条件</h3><p>先绑定明确目标、明确车身坐标方向，再检查整个平移扫掠区、邻车余量及静态环境。若表示真实行驶，还须检查转向与随时间的轨迹。仅在此基础上才评价新位置的渲染。几何候选扫描发现 scene_0230 前移 1 m 的最小框间距约 0.54 m、scene_0255 前移 2 m 约 0.71 m；它们目前只是候选，不是本轮已确认合法或已执行的结果。</p>
<p class="muted">无新模型前向、零训练；本轮使用 GT 是诊断控制，非 RGB 端到端自动能力。保留已知困难的两个开发 scene，未改变分母。人工 verdict 由用户填写。<a href="review_data.json">时序索引</a> · <a href="audit_report.md">审计报告</a></p></section><footer>图像可点击查看全尺寸；视频可全屏与暂停。黑色裁剪边缘表示原图之外，不是新生成的背景洞。</footer></main>
<script>const data=__DATA__;for(const section of document.querySelectorAll('[data-scene]')){const r=data.scenes.find(x=>x.name===section.dataset.scene),vs=[...section.querySelectorAll('video')],slider=section.querySelector('.scrub'),stamp=section.querySelector('output');function label(i){const f=r.frames[i];stamp.textContent=`f${String(f.frame).padStart(3,'0')} · ${(f.frame/10).toFixed(1)} s · CAM${f.camera}`;}function seek(){const i=Number(slider.value);vs.forEach(v=>{v.pause();v.currentTime=i/r.fps+.001});label(i)}slider.oninput=seek;section.querySelector('.play').onclick=()=>{const t=Number(slider.value)/r.fps;vs.forEach(v=>{v.currentTime=t;v.play().catch(()=>{})})};section.querySelector('.pause').onclick=()=>vs.forEach(v=>v.pause());vs[0].ontimeupdate=()=>{if(!vs[0].paused){const i=Math.min(9,Math.floor(vs[0].currentTime*r.fps));slider.value=i;label(i);vs.slice(1).forEach(v=>{if(Math.abs(v.currentTime-vs[0].currentTime)>.2)v.currentTime=vs[0].currentTime;})}};label(0)}</script></body></html>'''
(O/'index.html').write_text(head+'\n'.join(sections)+tail.replace('__DATA__',json.dumps(D,ensure_ascii=False)),encoding='utf-8')
old=O.parent/'v77-explicit-poc'/'index.html';backup=old.with_name('index_pre_audit.html')
if not backup.exists():shutil.copy2(old,backup)
text=backup.read_text(encoding='utf-8')
banner='<div style="padding:22px;background:#8d203d;color:white;font:18px/1.8 sans-serif"><strong>审计更正：本页是旧结果，旧资产失败及关闭结论已撤回。</strong>scene_0230 的 MOVE 撞到邻车 GT 框，原位车头放反；scene_0255 仍未通过指令准入。<a style="color:white;text-decoration:underline" href="../v77-actor-audit/index.html">请打开新目标与指令审计页 →</a></div>'
old.write_text(text.replace('<body>','<body>'+banner,1),encoding='utf-8')
print(O/'index.html')
