"""九例完全同构的三列审核页，默认纯几何读出，RGB回填显式可选。"""
from pathlib import Path
import json,html,argparse
p=argparse.ArgumentParser();p.add_argument('--output',type=Path,required=True);a=p.parse_args();R=a.output
reg=json.loads((R/'evidence/effective_registration.json').read_text(encoding='utf-8'));obs=json.loads((R/'observations.json').read_text(encoding='utf-8'))
esc=lambda x:html.escape(str(x))
svg='''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1100 250"><defs><marker id="a" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="#7096ba"/></marker></defs><style>rect{fill:#203951;stroke:#6689a8;rx:10}text{fill:#eff6ff;text-anchor:middle;font:17px sans-serif}.s{font-size:13px;fill:#b8cede}path.f{fill:none;stroke:#7096ba;stroke-width:2;marker-end:url(#a)}</style>'''
nodes=[(10,22,145,68,'九例RGB视频','每例30帧×6相机'),(195,22,150,68,'SAM2实例mask','同一GT提示规则'),(385,22,175,68,'DriveEditor补景','同一seed与写回'),(600,22,170,68,'冻结Ω背景 B_t','GT相机＋LiDAR尺度'),(195,150,200,68,'冻结Hunyuan GLB','同一选帧与形状/贴图规则'),(835,22,235,68,'原位重建：B_t＋GLB','固定位置/尺寸/光照'),(835,150,235,68,'DELETE：同一 B_t','只把GLB visible置false')]
for x,y,w,h,title,sub in nodes:svg+=f'<rect x="{x}" y="{y}" width="{w}" height="{h}"/><text x="{x+w/2}" y="{y+29}">{title}</text><text class="s" x="{x+w/2}" y="{y+51}">{sub}</text>'
for d in ['M155 56 H195','M345 56 H385','M560 56 H600','M770 56 H835','M80 90 V184 H195','M395 184 H795 V56 H835','M685 90 V184 H835']:svg+=f'<path class="f" d="{d}"/>'
(R/'architecture.svg').write_text(svg+'</svg>',encoding='utf-8')
page='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>v77｜九例统一规则完整DELETE</title><style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#0c1622;color:#e6eef8;font:16px/1.7 system-ui,"Microsoft YaHei",sans-serif}main{max-width:1580px;margin:auto;padding:30px}h1{font-size:32px;line-height:1.3}h2{font-size:25px;line-height:1.4}p{max-width:1240px}section{background:#152337;border:1px solid #344b63;border-radius:12px;margin:28px 0;padding:24px}a{color:#9bd0ff}nav{display:flex;flex-wrap:wrap;gap:10px 22px}.tag{display:inline-block;background:#27465f;padding:4px 12px;border-radius:16px;margin:0 8px 6px 0}.note{background:#292b29;border-left:4px solid #dfb54e;padding:12px 18px}.columns{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}figure{margin:0}figcaption{min-height:85px}small{display:block;color:#b9cbdc}video{display:block;width:100%;background:#000}button,select{font-size:14px;padding:8px 12px;border-radius:6px;border:1px solid #7092b1;background:#22435f;color:#fff}.controls{display:flex;flex-wrap:wrap;align-items:center;gap:10px;margin:18px 0}.sheet{display:block;max-width:100%;height:auto;margin:14px 0}.crop{max-width:300px;max-height:200px;background:#626a72}details{margin:20px 0}summary{cursor:pointer;color:#a7d3ff}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #38516a;text-align:left;vertical-align:top}code{font-size:13px;overflow-wrap:anywhere}footer{color:#bdcddd;margin:30px 0}@media(max-width:800px){main{padding:12px}section{padding:14px}.columns{grid-template-columns:1fr}figcaption{min-height:0;margin:10px 0}}</style><main>'''
page+='<h1>v77：九个 scene，统一 r30 迁移配置完整 DELETE</h1><p>每行三列：<b>原视频 → 原位重建 → 重建后 DELETE</b>。三列封面使用同一个目标投影最大帧，点击同步播放从第0帧开始。九例全部是已经接触过的开发场景，本轮用于统一流程对比，不是独立泛化评测。旧 r18／r21／r30 没有充当本轮输出。</p>'
page+='<p class="note">默认显示纯几何背景＋显式GLB，黑洞就是实际缺少几何支持。可切换“输入RGB回填”，只填没有几何命中的位置；该模式画面更完整，但不能证明背景几何完整。中间列不是原图复制，也不是直接对原视频跑Ω：它是补景后的背景B_t，加回原位目标GLB。</p><p>'+esc(obs['overview'])+'</p><nav>'
for s in reg['scenes']:page+=f'<a href="#{s["name"]}">{esc(s["name"])}</a>'
page+='</nav><section><h2>本轮统一配置</h2><img class="sheet" src="architecture.svg" alt="九例统一pipeline组件图"><p>从r30整理出同一套可复用补景与写回规则，九例按这套配置重新执行；不是直接复用旧r30视频。统一首30个连续时刻、10Hz回放约3秒，六相机参与背景重建。SAM2.1-large用GT框提示；DriveEditor固定seed42、25步、10帧窗口0/9/18/27；同一矩形条件、8像素羽化与邻车保护。Hunyuan固定seed7740，单次shape＋PBR；每例按实例mask面积选同一30帧内的最大可见参考。Ω和Hunyuan均冻结，训练0步。</p><p>六相机统一采用GT相机、目标GT位姿/尺寸/高度与LiDAR尺度辅助。B_t逐时刻重建，其他车辆大多仍在背景。GLB统一使用水平PCA对齐长轴、真实参考0/180方向判别和固定光照。全部输入、参数与工程修正见共同配置，人工评价留空。</p><p><a href="../v77-expansion/index.html">上一轮扩展报告</a> · <a href="../v77-hybrid-delete/index.html">历史修复结果</a> · <a href="evidence/effective_registration.json">本轮最终共同配置</a> · <a href="evidence/engineering_amendment_01.json">轴向工程修正记录</a></p></section>'
for s in reg['scenes']:
    name=s['name'];folder=R/'media'/name;st=json.loads((folder/'summary.json').read_text(encoding='utf-8'));o=obs['scenes'][name];root='media/'+name
    page+=f'<section id="{name}" class="case" data-root="{root}"><h2>{esc(name)} · 删除 actor {esc(s["actor"])}</h2><span class="tag">30帧／约3秒</span><span class="tag">主视角 CAM{st["primary_camera"]}</span><span class="tag">已接触开发例</span><p><b>目标：</b>{esc(o["identity"])}</p>'
    page+=f'<p><small>目标有GT投影的相机×时刻共{st["gt_visible_view_times"]}个，其中{st["mask_missing_when_gt_visible"]}个没有write mask；这是“出视野／真实遮挡／分割缺失”待区分的记录，不能一概判跟踪失败。该例实际渲染GLB层{st["actual_layer_renders"]}张。主视角按GT可见时刻数最多选，平局再按累计面积，不按生成效果挑选。</small></p>'
    page+='<div class="controls"><button class="play">从头同步播放</button><button class="pause">暂停</button><label>画面 <select class="view"><option value="main">固定主视角</option>__EXTRA_CAMERA_OPTIONS__<option value="zoom">目标区域放大（三列同范围）</option><option value="six">六相机同屏</option></select></label><label>渲染 <select class="mode"><option value="pure">纯几何（默认）</option><option value="hybrid">输入RGB回填</option></select></label><label>速度 <select class="speed"><option>1</option><option>0.5</option><option>0.25</option></select></label></div><div class="columns">'
    for label,k,note in [('原视频','original','同一时间与相机。黄框标出GT目标位置；放大模式三列使用同一个固定裁剪。'),('原视频的原位重建','factual','补景背景经Ω重建，再放回该目标的新GLB。'),('重建视频编辑：DELETE','delete','读取同一背景，只关闭目标GLB可见性。')]:page+=f'<figure><figcaption><b>{label}</b><small>{note}</small></figcaption><video controls muted playsinline preload="metadata" poster="{root}/poster_{k}.jpg" data-kind="{k}" src="{root}/{k}.mp4"></video><a class="direct" href="{root}/{k}.mp4">单独打开视频</a></figure>'
    page=page.replace('__EXTRA_CAMERA_OPTIONS__',''.join(f'<option value="cam{v["camera"]}">CAM{v["camera"]}（目标其他视角）</option>' for v in s['streams'] if v['active'] and v['camera']!=st['primary_camera']))
    page+='</div><p class="mode-note">当前为纯几何：缺失支持显示黑色；没有用原RGB补黑洞。</p>'
    page+=f'<details><summary>目标参考、资产与中间产物（可选）</summary><p>下图是本轮自动选出的真实实例crop；不把未观测表面当作真实证据。</p><img class="crop" src="{root}/source_rgba.png" alt="目标实例参考"><p><a href="{root}/actor.glb">下载该例实际使用的GLB</a> · <a href="{root}/scope.mp4">mask范围视频</a> · <a href="{root}/completion.mp4">补景写回视频（尚未经过Ω）</a></p><img class="sheet" loading="lazy" src="{root}/asset_views.jpg" alt="实际形状与材质八视角，前后方向烘焙前"><p>同一真实参考的0/180方向控制，仅用于BUILD拟合：</p><a href="{root}/orientation_contact.jpg"><img class="sheet" loading="lazy" src="{root}/orientation_contact.jpg" alt="真实参考方向控制"></a><p>真实目标与其他GT车辆包络交叠提示（黄色目标、青色邻车；包络不是精确可见轮廓）：</p><img class="sheet" loading="lazy" src="{root}/neighbor_source.jpg" alt="目标与真实邻车提示"><p>十个时点的原视频／原位重建／DELETE：</p><a href="{root}/contact.jpg"><img class="sheet" loading="lazy" src="{root}/contact.jpg" alt="三列逐帧联系图"></a><p>同一轮保存的中间产物：mask → DriveEditor原生 → 写回 → Ω纯几何。</p><a href="{root}/stages.jpg"><img class="sheet" loading="lazy" src="{root}/stages.jpg" alt="补景和重建分阶段联系图"></a></details></section>'
page+='<section><h2>审核范围</h2><p>本轮仅提供九例同配置的完整三列对照，不在页面填写质量归因或人工通过结论。可切换目标其他视角、六相机同屏、目标区域放大和回放速度。旧结果保留在历史报告中。</p></section><footer>WS-V77-NINE-FULL-20260928 / r1。原始帧、模型输出、点云、GLB、RGBA/深度层和失败记录均保留；没有覆盖历史产物。默认视频688×384，模型补景1024×576。浏览器交互验证状态见 validation.json。</footer><script src="review.js"></script></main></html>'
(R/'index.html').write_text(page,encoding='utf-8')
js='''document.querySelectorAll('.case').forEach(c=>{const vs=[...c.querySelectorAll('video')],speed=c.querySelector('.speed');function source(){const view=c.querySelector('.view').value,hy=c.querySelector('.mode').value==='hybrid';vs.forEach(v=>{v.pause();v.removeAttribute('poster');let k=v.dataset.kind;if(hy&&k!=='original')k='hybrid_'+k;if(view!=='main')k=view+'_'+k;v.src=c.dataset.root+'/'+k+'.mp4';v.closest('figure').querySelector('.direct').href=v.src;v.load();v.playbackRate=Number(speed.value)});c.querySelector('.mode-note').textContent=hy?'当前启用输入RGB回填：只填无几何命中区域，不能据此认为几何完整。':'当前为纯几何：缺失支持显示黑色；没有用原RGB补黑洞。'}c.querySelector('.view').onchange=source;c.querySelector('.mode').onchange=source;c.querySelector('.play').onclick=async()=>{vs.forEach(v=>v.currentTime=0);await Promise.allSettled(vs.map(v=>v.play()))};c.querySelector('.pause').onclick=()=>vs.forEach(v=>v.pause());speed.onchange=()=>vs.forEach(v=>v.playbackRate=Number(speed.value));vs[0].addEventListener('timeupdate',()=>{if(!vs[0].paused)vs.slice(1).forEach(v=>{if(Math.abs(v.currentTime-vs[0].currentTime)>.12)v.currentTime=vs[0].currentTime})})});'''
(R/'review.js').write_text(js,encoding='utf-8');print('HTML_BUILT',R/'index.html')
