"""本地审核页；模型原生与写回、纯几何与RGB回填分栏。"""
from pathlib import Path
import json,html,shutil,argparse
ap=argparse.ArgumentParser();ap.add_argument('--stage',type=Path,default=Path(__file__).resolve().parent);ap.add_argument('--output',type=Path);args=ap.parse_args();STAGE=args.stage
OUT=args.output or STAGE.parents[1]/'outputs/v77-expansion';OUT.mkdir(parents=True,exist_ok=True)
obs=json.loads((STAGE/'observations.json').read_text(encoding='utf-8'))
def esc(x):return html.escape(str(x))
def group(items,key):
    text=f'<div class="controls"><button data-play="{key}">从头同步播放</button><button data-pause="{key}">暂停</button><label>速度 <select data-rate="{key}"><option>1</option><option>0.5</option><option>0.25</option></select></label></div><div class="videos" data-group="{key}">'
    for label,path,note in items:text+=f'<figure><figcaption><strong>{esc(label)}</strong><small>{esc(note)}</small></figcaption><video controls muted playsinline preload="metadata" src="{esc(path)}"></video><a href="{esc(path)}">单独打开视频</a></figure>'
    return text+'</div>'
def image(path,label):return f'<a href="{esc(path)}"><img class="contact" loading="lazy" src="{esc(path)}" alt="{esc(label)}"></a>'
svg='''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1160 330"><defs><marker id="a" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="#8ba6c8"/></marker></defs><style>rect{fill:#213954;stroke:#537ea7;rx:10}text{fill:#edf3fc;font:17px sans-serif;text-anchor:middle}.s{font-size:13px;fill:#b9cde3}path.flow{stroke:#8ba6c8;stroke-width:2;fill:none;marker-end:url(#a)}</style>'''
nodes=[(15,30,160,70,'多相机真实视频','9例固定身份'),(215,30,160,70,'SAM2 实例 mask','GT box 作提示'),(415,30,190,70,'DriveEditor deletion','固定矩形洞／保护写回'),(650,30,190,70,'原生＋合成视频审核','未通过不接 Ω'),(885,30,240,70,'r30 → 冻结 Ω','首10帧／GT相机＋LiDAR尺度'),(650,165,190,70,'Hunyuan GLB','冻结模型／显式 actor'),(885,165,240,70,'背景 B_t ＋编辑渲染','INSERT／factual／MOVE'),(15,245,240,65,'独立真实背景候选','车辆尺度 mask → 原 RGB监督'),(310,245,240,65,'数据审核与固定评测','正式训练尚未启动')]
for x,y,w,h,title,sub in nodes:svg+=f'<rect x="{x}" y="{y}" width="{w}" height="{h}"/><text x="{x+w/2}" y="{y+29}">{title}</text><text class="s" x="{x+w/2}" y="{y+51}">{sub}</text>'
for d in ['M175 65 H215','M375 65 H415','M605 65 H650','M840 65 H885','M1005 100 V165','M840 200 H885','M95 100 V200 H650','M255 277 H310']:svg+=f'<path class="flow" d="{d}"/>'
svg+='</svg>';(OUT/'architecture.svg').write_text(svg,encoding='utf-8')
page='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>v77｜九场景扩展与编辑工程</title><style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#0e1723;color:#e8eef6;font:16px/1.7 system-ui,"Microsoft YaHei",sans-serif}main{max-width:1500px;margin:auto;padding:30px}h1{font-size:34px;margin:0 0 12px}h2{font-size:25px;margin:0 0 12px}h3{font-size:19px}section{background:#152235;border:1px solid #34465e;border-radius:12px;padding:24px;margin:24px 0}p{max-width:1100px}a{color:#a3d5ff}nav{display:flex;flex-wrap:wrap;gap:20px}small{display:block;color:#bbcbdc}.tag{display:inline-block;padding:4px 12px;background:#29465d;border-radius:20px;margin-right:8px}.warn{padding:14px 18px;border-left:4px solid #efb44f;background:#302b26}.videos{display:grid;grid-template-columns:repeat(auto-fit,minmax(310px,1fr));gap:16px}figure{margin:0}figcaption{min-height:88px}video{width:100%;background:#000;display:block}figure a{font-size:13px}.controls{display:flex;align-items:center;gap:10px;margin:12px 0}button,select{background:#244467;color:#fff;border:1px solid #6885a4;border-radius:6px;padding:8px 12px;font-size:14px;cursor:pointer}img.contact{max-width:100%;height:auto;display:block;margin:12px 0}details{margin:18px 0}summary{cursor:pointer;color:#a3d5ff}table{border-collapse:collapse;width:100%}td,th{border-bottom:1px solid #35465a;padding:10px;text-align:left;vertical-align:top}code{font-size:13px;overflow-wrap:anywhere}.stats{display:flex;gap:24px;flex-wrap:wrap}.stat{padding:12px 20px;background:#203750;border-radius:10px}.stat b{font-size:26px;display:block}footer{color:#afbed0;margin:30px 0}@media(max-width:720px){main{padding:14px}section{padding:16px}.videos{grid-template-columns:1fr}table{font-size:13px}}</style><main>'''
page+='<h1>v77：九场景扩展与编辑工程</h1><p>把补景、几何、资产放置分开验证。保留旧三例及用户对 scene_0255 的 <b>r18 &gt; r15</b> 判断；新增六例按同一配置运行，不对留出例逐场景修补。</p><div class="stats"><div class="stat"><b>3 + 6</b>旧例保留＋新增评测</div><div class="stat"><b>5 / 6</b>新增例完成30帧生成，非成功率</div><div class="stat"><b>0</b>训练步数</div><div class="stat"><b>78</b>背景监督候选，尚未准入训练</div></div>'
page+='<nav><a href="#cohort">六例视频</a><a href="#omega">r30接回Ω</a><a href="#insert">INSERT</a><a href="#actor">目标原位／MOVE</a><a href="#data">数据准备</a><a href="#limits">范围与下一步</a></nav>'
page+='<section><h2>本轮实际发现</h2><p>'+esc(obs['headline'])+'</p><p class="warn">本页为工程与视觉诊断报告；所有新 human_verdict 留空。新增五例生成完成不等于五例通过。夜间例输入 mask 未准入，仍计入六例分母；跨相机 DELETE 尚未验证完成。</p>'+image('architecture.svg','pipeline组件图')+'</section>'
page+='<section id="cohort"><h2>固定九例：旧三例保留，新增六例</h2><p>新增开发例：350、663、191。新增本轮留出例：425、382、756。原始图像和几何先选样，再固定 SAM2.1-large／seed42／25步／1024×576／10帧窗口；起点0、9、18、27，同时间重叠，末窗补齐但输出只保留30个真实时刻。处理后10Hz回放约3秒，精确原始相机时间戳未知。</p><p>模型输入洞为实例 mask 外接框：左右及上方8px、下方24px；写回采用8px羽化，精确目标区权重1，目标外其他GT对象包络权重0。邻车保护包络不是精确可见性真值，栏杆等静态结构仍需逐帧检查。没有把不合格的 warp 当成真实背景证据。</p><table><tr><th>Scene／目标</th><th>角色</th><th>本轮证据与判断</th></tr>'
for name,role,desc,url in [('scene_0230／22','旧开发','困难例与全部反例保留，本轮未重跑','../v77-hybrid-delete/index.html'),('scene_0255／25','旧开发','继续保留r18/r21；真实邻车52不能误判为幻觉','../v77-hybrid-delete/fence-writeback/index.html'),('official_000／12','旧开发','r30首10帧接回Ω；其他真实对象仍在背景','../v77-hybrid-delete/third-scene-temporal/index.html')]:page+=f'<tr><td><a href="{url}">{name}</a></td><td>{role}</td><td>{desc}</td></tr>'
for s in obs['scenes']:page+=f'<tr><td><a href="#{s["id"]}">{esc(s["label"])}</a></td><td>{esc(s["split"])}</td><td>{esc(s["result"])}</td></tr>'
page+='</table><p><small>已排除179=scene_0230、204=scene_0255两个旧别名。新增三例留出仅表示本轮未调参；历史V5数据使用、预训练重叠未知，不称独立外部测试。无原始日志重叠的检查范围见证据文件。</small></p></section>'
for s in obs['scenes']:
    root='media/'+s['id'];page+=f'<section id="{s["id"]}"><h2>{esc(s["label"])}</h2><span class="tag">{esc(s["split"])}</span><span class="tag">CAM{s["camera"]} · 30帧</span><p><b>删谁：</b>{esc(s["identity"])}</p><p><b>观察：</b>{esc(s["result"])}</p>'
    if s['generated']:items=[('原画面＋黄色目标',root+'/target.mp4','黄色轮廓为实例写回范围；框为GT提示范围。'),('DriveEditor 原生输出',root+'/native.mp4','看生成阶段是否已出现错误结构／车型。'),('最终 DELETE',root+'/delete.mp4','带羽化和邻车保护写回；与中栏分开判断。')]
    else:items=[('原视频',root+'/original.mp4','夜间车流，目标可见性与跟踪仍待拆解。'),('目标与当前SAM',root+'/target.mp4','多数帧为空；黄色框不等于有效实例mask。'),('当前模型mask／保护区',root+'/scope.mp4','未执行DriveEditor；这不是补景结果。')]
    page+=group(items,s['id'])+f'<details><summary>原视频、mask范围与10个时点放大图</summary><p>蓝色：模型补景洞；青色：GT对象保护包络。放大图只用于抽检，不等于全片时序通过。</p><a href="{root}/original.mp4">无标记原视频</a> · <a href="{root}/scope.mp4">补景与保护范围视频</a>'+image(root+'/crops.jpg','10个时点目标区域对照')
    if s['id']=='processed_382':page+='<p>下图青框11为真实隐藏邻车。后续应核对它的身份、位置与形状，不能看到一辆车就记幻觉。</p>'+image('media/neighbor382.jpg','382真实隐藏邻车核对')
    page+='</details></section>'
page+='<section id="omega"><h2>r30 → 冻结 Ω：完成首10帧几何回接</h2><p>official_000／actor12，CAM0使用原样保存的r30；其余五相机使用原RGB。已核对这10帧中目标12在其他五相机GT投影面积为0。每时刻独立六相机重建，仍使用GT相机与背景LiDAR尺度，不是跨时刻持久世界。</p><p>删除区在纯几何读出中保持了r30外观；远处树木、天空有明显孔洞。第四栏只在无几何命中像素回填输入RGB，因此不能用第四栏完整画面证明几何完整。相机回放也不是未见视角评测。</p>'
page+=group([('原视频','media/omega/original.mp4','10帧／1秒，原始目标仍可见。'),('r30 补景输入','media/omega/input_r30.mp4','既有结果原样复用，无重跑生成。'),('纯 Ω 点几何','media/omega/geometry.mp4','直接暴露几何无支持区域。'),('几何＋输入RGB回填','media/omega/hybrid.mp4','只填无命中像素；不是新增几何。')],'omega')+'<details><summary>逐帧局部对照</summary>'+image('media/omega/all10_crops.jpg','r30几何首10帧')+'</details></section>'
page+='<section id="insert"><h2>INSERT：原有GLB放到空道路位置</h2><p>使用 scene_0255／25 的原有GLB，作为 official_000 的新增车辆；不冒充目标12。选择 proposal2，尺寸4.974×2.055×1.925m。30帧几何筛选最小其他对象间距3.55m、ego包络间距1.24m；仅支持有界工程检查，不能当完整道路合法证明。</p><p>下面10帧、约1秒：位置随相机运动保持稳定；固定光照、缺少接触阴影仍有明显合成感。CAM4只在画面边缘短暂看到资产，不能据此宣布两视角连续3秒通过。</p>'
page+=group([('背景','media/insert/cam5_source.mp4','CAM5，目标新增位置为空道路。'),('GLB无背景遮挡测试','media/insert/cam5_no_occlusion.mp4','固定mesh和世界位姿，先检查尺寸与朝向。'),('GLB＋Ω深度遮挡','media/insert/cam5_omega_occlusion.mp4','相同资产，相同位姿；只加入背景深度测试。')],'insert')
page+='<details><summary>相邻CAM4、纯几何对照与占地检查</summary>'+group([('CAM4背景','media/insert/cam4_source.mp4','资产可能仅边缘可见。'),('CAM4插入','media/insert/cam4_omega_occlusion.mp4','未对空视角伪造可见资产。'),('CAM5纯几何插入','media/insert/cam5_pure_geometry.mp4','显式展示背景远景孔洞。')],'insert_side')+image('media/footprints.jpg','候选位置的地面占地轮廓')+'</details></section>'
page+='<section id="actor"><h2>原位还原与 MOVE</h2><p>'+esc(obs['actor'])+'</p><p>'+esc(obs['move'])+'</p>'
if (OUT/'media/actor/factual.mp4').exists():
    page+=group([('原视频＋目标12框','media/actor/original.mp4','黄色框明确原位位置。'),('r5：按GT高度原位放回','media/actor/factual.mp4','先暴露GT框离地和当前外观问题。'),('r7：固定下移14.61cm','media/ground/grounded.mp4','只改Z；同一GLB、背景与光照，不代表外观通过。')],'actor')
    page+='<p>GT框底部比局部路面平面高12.8–16.0cm。网格变换后实际包围盒与指定框核对通过；r7只用首帧测量下移14.61cm作接地对照。路面支持离目标约2.34m，其他时刻可达6.84m，因此仍是平面外推诊断，不能当轮胎接触点真值。接地与PBR/照明问题分开记。</p>'+image('media/ground/contact.jpg','原位高度单变量对照')
    page+='<details><summary>资产8视角、0/180度与原位局部对照</summary>'+image('media/actor12_shape.jpg','网格8视角')+image('media/actor12_pbr.jpg','PBR8视角')+image('media/actor12_pose.jpg','已知可见视角的朝向控制')+image('media/actor/crops.jpg','首10帧原位放回')+'<p><a href="media/actor/no_occlusion.mp4">不加背景遮挡控制</a> · <a href="media/actor/pure_geometry.mp4">纯几何背景控制</a> · <a href="media/actor12.glb">下载此失败诊断GLB</a></p></details>'
page+='<details><summary>真实参考与MOVE候选几何检查</summary>'+image('media/source12_views.jpg','目标12真实多视角选帧')+image('media/move_candidates.jpg','四个0.5米MOVE候选')+'</details></section>'
page+='<section id="data"><h2>训练准备：78个候选，还不是可训练数据集</h2><p>三个额外scene，共78个mask片段候选，来自28段相机短片、16个不重叠时间窗；train候选34、validation候选44。每段30帧，车辆尺度3D包络投影为mask，带洞输入以真实原RGB为恢复目标。生成补景从未用作GT。</p><p>2340张mask完成GT对象交叠筛选；156个首尾输入合同检查通过。抽查样例仍包含人行道、树木和过暗画面，需要逐片审核。训练候选主要白天，验证候选为夜间域偏移，尚非平衡划分。当前资料不足以称200–500个独立合格短片，所有 training_admitted=false。</p><p>与新增六例及旧0230/0255未发现已知原始日志交叠，全部九例与数据池没有相同actor track；official_000原日志身份尚缺，必须在正式训练前补齐，track不重复不能替代完整日志隔离。</p>'
for sid,title in [('276','白天道路'),('296','路缘与建筑结构'),('827','夜间压力例')]:page+='<details><summary>'+title+'：真实监督样例</summary>'+group([('遮挡输入',f'media/data/{sid}_input.mp4','零值洞仅作为输入；未训练模型。'),('真实恢复目标',f'media/data/{sid}_target.mp4','未生成的原RGB，不是伪GT。')],f'data{sid}')+'</details>'
page+='</section><section id="limits"><h2>本轮边界与下一步</h2><p>'+esc(obs['next'])+'</p><p>正式训练仍需：固定评测在多个场景重复暴露同一模型问题，排除mask／标定／写回错误；可信、隔离的监督数据；一次反向传播显存实测。推理显存不能直接推断24GB可训练。Ω和资产模型继续冻结。</p><p>技术来源：<a href="https://github.com/facebookresearch/vggt-omega#quick-start">Ω官方接口</a> · <a href="https://github.com/yvanliang/DriveEditor#-train-the-model">DriveEditor官方训练入口</a>。图像审核为助手观察；用户最终判断单独记录。</p></section><footer>任务 WS-V77-EXPAND-EDIT-20260928 · r1–r7。旧版本及失败产物均保留。页面检查：图片与视频解码、静态引用和JS语法；浏览器交互未实测。详细运行证据见 evidence/。</footer>'
js='''function vids(k){return [...document.querySelector(`[data-group="${k}"]`).querySelectorAll('video')]}document.querySelectorAll('[data-play]').forEach(b=>b.onclick=async()=>{const v=vids(b.dataset.play);v.forEach(x=>x.currentTime=0);await Promise.allSettled(v.map(x=>x.play()))});document.querySelectorAll('[data-pause]').forEach(b=>b.onclick=()=>vids(b.dataset.pause).forEach(x=>x.pause()));document.querySelectorAll('[data-rate]').forEach(b=>b.onchange=()=>vids(b.dataset.rate).forEach(x=>x.playbackRate=Number(b.value)));document.querySelectorAll('[data-group]').forEach(g=>{const v=[...g.querySelectorAll('video')],lead=v[0];lead.addEventListener('timeupdate',()=>{if(!lead.paused)v.slice(1).forEach(x=>{if(Math.abs(x.currentTime-lead.currentTime)>.15)x.currentTime=lead.currentTime})})});'''
(OUT/'review.js').write_text(js,encoding='utf-8');page+='<script src="review.js"></script></main></html>';(OUT/'index.html').write_text(page,encoding='utf-8');print(OUT/'index.html')
