"""本地审核页；以导出的JSON和视频为唯一计数来源。"""
import argparse,html,json,pathlib
BASE=pathlib.Path(__file__).resolve().parents[2]
p=argparse.ArgumentParser();p.add_argument('--output',type=pathlib.Path,default=BASE/'outputs/v77-delete-full');OUT=p.parse_args().output
data=json.loads((OUT/'summary.json').read_text(encoding='utf-8'))
obs=json.loads((OUT/'observations.json').read_text(encoding='utf-8'))
arch='''<div class="arch"><div>六相机 RGB<br><small>GT 提示的已有 SAM2 mask</small></div><b>→</b><div>DriveEditor deletion<br><small>24 窗 · 冻结权重 · 不训练</small></div><b>→</b><div>VGGT-Ω 512<br><small>150 次六相机重建</small></div><b>→</b><div>每时刻背景 Bₜ<br>＋已有 actor.glb</div><b>→</b><div>QUERY: DELETE<br><small>仅 visible = false</small></div></div>'''
css='''*{box-sizing:border-box}body{margin:0;background:#f3f5f8;color:#1d2a3c;font:16px/1.65 system-ui,"Microsoft YaHei",sans-serif}main{max-width:1600px;margin:auto;padding:30px}h1{font-size:34px;margin:8px 0}h2{margin:6px 0;font-size:25px}h3{margin:0;font-size:17px}p{margin:10px 0}a{color:#245ca7}section,.intro{background:white;border:1px solid #dce2ea;border-radius:14px;padding:24px;margin:22px 0}.muted,small{color:#647386}small{font-size:13px}.tag{display:inline-block;background:#e6edf7;padding:4px 10px;border-radius:6px;font-size:13px}.warning{background:#fff1dc;border-left:4px solid #be7b17;padding:12px 16px}.arch{display:flex;align-items:center;gap:12px;margin:22px 0;overflow:auto}.arch div{background:#eaf0f8;border:1px solid #c6d5e9;border-radius:8px;padding:13px;text-align:center;min-width:175px}.cols{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.two{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}video{width:100%;background:#10151c;border-radius:6px;display:block}figure{margin:0}figcaption{font-size:14px;margin:9px 0}button,select{background:white;border:1px solid #b7c7db;border-radius:6px;padding:9px 13px;cursor:pointer;color:#243c5e}button:hover{background:#edf3fa}.controls{display:flex;gap:9px;align-items:center;flex-wrap:wrap;margin:18px 0}.controls input{flex:1;min-width:150px}.checks{display:flex;gap:22px;flex-wrap:wrap;font-size:14px}.checks b{font-size:21px;display:block}details{margin:20px 0;border-top:1px solid #dee5ef;padding-top:12px}summary{cursor:pointer;font-weight:600}img{max-width:100%;height:auto}table{border-collapse:collapse;width:100%;font-size:14px}td,th{text-align:left;padding:10px;border-bottom:1px solid #e0e6ee}.note{background:#eef3f8;padding:12px 16px;border-radius:7px}code{overflow-wrap:anywhere}@media(max-width:1000px){main{padding:12px}.cols,.two{grid-template-columns:1fr}.arch{font-size:13px}h1{font-size:27px}}'''
css+=' .all-cameras .cols{grid-template-columns:1fr}.all-cameras .cols figure{width:100%;max-width:1250px;margin:auto}'
sections=[]
for s in data['scenes']:
    name=s['scene'];o=obs[name];cov=s['geometry_coverage_min_mean'];mcov=s['deletion_mask_geometry_coverage_min_mean'];occ=1-s['visible_asset_pixels']/max(s['asset_pixels'],1)
    cards=''
    for k,title,caption in [('original','① 原视频 · 黄标目标',f'黄色只标出 actor {s["actor_id"]} 的 SAM2 可见区域。跟随视图切换相机时，左上角 CAM 编号会改变。'),('factual','② 原位 factual · Bₜ + GLB','用本轮 DriveEditor 背景重建 Bₜ，再放回同一 GLB。GT 位姿/尺寸，保留已修正的朝向与相机。固定照明，无阴影重建。'),('delete','③ 执行 DELETE · 同一 Bₜ','只关闭显式 GLB。若仍有车辆轮廓，那是补景/背景几何中的残留，并非 DELETE 指令又加载了 GLB。')]:
        cards+=f'<figure><h3>{title}</h3><video class="sync" data-kind="{k}" src="{name}/{k}.mp4" controls preload="metadata" playsinline muted loop></video><figcaption>{caption}</figcaption></figure>'
    texts=''.join(f'<li>{html.escape(v)}</li>' for v in o['observations'])
    cross=s['cross_camera_relative_depth_over_10pct_fraction'];crosslabel=f'{cross:.1%}' if cross is not None else '无共同样本'
    sections.append(f'''<section id="{name}" data-scene="{name}" data-duration="{s['duration_s']}"><span class="tag">{name} / actor {s['actor_id']} / {s['frame_count']} 帧 / {s['duration_s']:g} 秒</span><h2>{html.escape(o['title'])}</h2><p>{html.escape(o['target'])}</p><div class="warning">{html.escape(o['verdict'])}</div>
    <div class="controls"><button class="play">三栏同步播放</button><button class="reset">回到开头</button><select class="mode"><option value="">跟随目标视角</option><option value="six_">全部六相机</option></select><select class="rate"><option value="1">1×</option><option value="0.5">0.5×</option><option value="0.25">0.25×</option></select><input class="seek" type="range" min="0" max="{s['duration_s']-.1}" step=".1" value="0"><span class="clock">0.0 s</span></div><div class="cols">{cards}</div>
    <h3>这段具体看什么</h3><ul>{texts}</ul><div class="checks"><span><b>{cov[0]:.1%} / {cov[1]:.1%}</b>纯几何画面覆盖率 · 最低 / 平均</span><span><b>{mcov[0]:.1%} / {mcov[1]:.1%}</b>删除 mask 内覆盖率 · 最低 / 平均</span><span><b>{occ:.1%}</b>GLB 投影像素被深度遮挡的比例</span><span><b>{crosslabel}</b>跨相机相对深度差 &gt;10% 的样本对</span></div><p class="muted">覆盖率仅说明有点投影，不证明补景正确；跨相机统计含真实遮挡、深度估计误差和生成不一致，不能解释为真值错误率或通过率。</p>
    <details><summary>补景输入与直接输出：先分清问题发生在哪一层</summary><div class="two"><figure><h3>实际删除 mask · 蓝色</h3><video controls muted loop preload="metadata" src="{name}/mask.mp4"></video></figure><figure><h3>DriveEditor 局部合成 · 尚未经过 Ω</h3><video controls muted loop preload="metadata" src="{name}/driveeditor.mp4"></video></figure></div><p>mask 外逐像素保留原 RGB。上方主三栏是经过 Ω 后的结果；本栏用于判断残留车形是否已经存在于补景阶段。</p></details>
    <details><summary>纯几何对照：灰色就是没有几何支持，不填源图</summary><div class="two"><figure><h3>原位 factual · 纯几何</h3><video controls muted loop preload="metadata" src="{name}/geometry_factual.mp4"></video></figure><figure><h3>DELETE · 纯几何</h3><video controls muted loop preload="metadata" src="{name}/geometry_delete.mp4"></video></figure></div><p>主三栏只在纯几何缺点像素用保存的 DriveEditor 背景 RGB 补足；不是覆盖整片 mask。这里完全关闭该补足。两类结果都使用相同的固定 3×3 点渲染及深度遮挡。</p></details>
    <details><summary>遮挡诊断：同一 GLB 不做深度测试时是否完整</summary><div class="two"><figure><h3>取消深度测试 · 仅作诊断</h3><video controls muted loop preload="metadata" src="{name}/unoccluded_factual.mp4"></video></figure><figure><h3>使用 Ω 背景深度 · 主结果</h3><video controls muted loop preload="metadata" src="{name}/factual.mp4"></video></figure></div><p>两段使用完全相同的 GLB、相机和背景，只切换深度测试。可辨别车身缺失是否来自背景遮挡；不做深度测试会错误盖住真实前景，不能把左侧当正确遮挡答案。</p></details>
    <details><summary>一张图看清各环节的差别</summary><p>第一行：源图 / DriveEditor 直接补景；第二行：Ω 纯几何 / 背景图补足后的 DELETE；第三行：同 GLB 关闭深度测试 / 开启深度测试。每行两张图，参数保持一致。</p><img src="{name}/diagnostic.jpg" alt="源图、补景、几何和遮挡分层截图"></details>
    <details><summary>10 个时间点静帧：原视频 / factual / DELETE</summary><img src="{name}/contact.jpg" alt="十个时刻三栏对照"></details>
    <details><summary>窗口接缝：同一时间的旧窗末帧 / 新窗首帧</summary><p>同一源帧作重叠条件；最终保留旧窗末帧，新窗重叠帧不重复输出。下面差异是同时间条件再生成的差异，不是车辆运动。</p><img src="{name}/seams.jpg" alt="同时间窗口接缝"></details>
    <p><a href="{name}/scene_factual.json">factual 场景清单</a> · <a href="{name}/scene_delete.json">DELETE 后清单</a> · <a href="{name}/command.json">结构化指令</a> · <a href="{name}/summary.json">逐帧统计</a></p></section>''')
script='''document.querySelectorAll('section[data-scene]').forEach(s=>{const vs=[...s.querySelectorAll('video.sync')],master=vs[0],seek=s.querySelector('.seek'),clock=s.querySelector('.clock');let locked=false;function align(t){vs.forEach(v=>{if(Number.isFinite(v.duration))v.currentTime=Math.min(t,v.duration-.01)});seek.value=t}function pause(){vs.forEach(v=>v.pause())}s.querySelector('.play').onclick=()=>{if(master.paused){vs.forEach(v=>v.play().catch(()=>{}))}else pause()};s.querySelector('.reset').onclick=()=>{pause();align(0)};seek.oninput=()=>{pause();align(+seek.value)};s.querySelector('.rate').onchange=e=>vs.forEach(v=>v.playbackRate=+e.target.value);s.querySelector('.mode').onchange=e=>{const t=master.currentTime;pause();vs.forEach(v=>{v.src=s.dataset.scene+'/'+e.target.value+v.dataset.kind+'.mp4';v.addEventListener('loadedmetadata',()=>v.currentTime=Math.min(t,v.duration-.01),{once:true});v.load()})};master.addEventListener('play',()=>vs.slice(1).forEach(v=>v.play().catch(()=>{})));master.addEventListener('pause',()=>vs.slice(1).forEach(v=>v.pause()));master.addEventListener('seeking',()=>{if(!locked){locked=true;vs.slice(1).forEach(v=>{if(Math.abs(v.currentTime-master.currentTime)>.08)v.currentTime=master.currentTime});locked=false}});function tick(){const t=master.currentTime;seek.value=t;clock.textContent=t.toFixed(1)+' s';if(!master.paused)vs.slice(1).forEach(v=>{if(Math.abs(v.currentTime-t)>.15)v.currentTime=t});requestAnimationFrame(tick)}tick()});'''
page=f'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>v77 DELETE 完整工程审核</title><style>{css}</style><main><span class="tag">WS-V77-DELETE-FULL-20260927 / r1 · 人工 verdict 留空</span><h1>v77 DELETE：从补景到显式资产删除</h1><p>两个场景，完整连续窗口，六相机。先看原视频 / 原位 factual / DELETE，再展开查看补景与纯几何诊断。</p><div class="intro"><h2>{html.escape(obs['headline'])}</h2><p>{html.escape(obs['overview'])}</p>{arch}<div class="note">BUILD 调用 DriveEditor 与 Ω，保存 Bₜ 和已有 GLB；QUERY 读取缓存并把目标 visible 设为 false。Bₜ 是逐时刻资产，不是持久静态世界，也不是已解决的 4D 重建。</div><p><a href="#scene_0230">scene_0230 / actor22</a> · <a href="#scene_0255">scene_0255 / actor25</a> · <a href="report.md">详细报告</a> · <a href="validation.json">检查记录</a></p></div>{''.join(sections)}<section><h2>输入、合法性与证据边界</h2><table><tr><th>项目</th><th>本轮实际做法</th></tr><tr><td>指令</td><td>DELETE 指定目标，无平移、无新增占据。助手看源帧核对身份与 mask；没有自动交通规则判定。两条旧 MOVE 仍拒绝。</td></tr><tr><td>模型</td><td>DriveEditor 官方训练后完整权重包，调用 deletion 分支；VGGT-Ω 512 冻结；复用原 SAM2 和 Hunyuan3D-2.1 GLB。零训练。</td></tr><tr><td>POC 真值辅助</td><td>GT 用于已有 SAM 提示/门控、相机内外参、actor 位姿与尺寸；GT 框外 LiDAR 只拟合 Ω 单个米制尺度。不是 RGB 端到端自动方案。</td></tr><tr><td>mask 门控</td><td>继承小目标与近裁面门控；无 mask 的视图复制原 RGB，可能留下未被处理的目标观测。当前只把指定目标拆成显式资产，其他 actor 仍在背景里。</td></tr><tr><td>遮挡与光照</td><td>GLB 相机 Z 与 Ω 点渲染 Z 比较，容差 0.15m；固定世界光和太阳光，无照明拟合、地面接触阴影或反射重建。几何误差可导致错误遮挡。</td></tr><tr><td>评价</td><td>两个已曝光开发场景；隐藏背景无真值，官方训练重叠未核对。视觉观察由助手记录，最终人工结论由用户填写。</td></tr></table></section></main><script>{script}</script></html>'''
page=page.replace('</script>',"document.querySelectorAll('.mode').forEach(e=>e.addEventListener('change',()=>e.closest('section').classList.toggle('all-cameras',e.value==='six_')));</script>")
(OUT/'index.html').write_text(page,encoding='utf-8')
print(OUT/'index.html')
