"""r23可见正控制与r24实际DELETE条件持续性报告。"""
from pathlib import Path
import json,argparse,re,html
p=argparse.ArgumentParser();p.add_argument('directory');root=Path(p.parse_args().directory)
read=lambda f:json.loads((root/f).read_text(encoding='utf-8-sig'))
template=(root.parent/'fence-writeback/index.html').read_text(encoding='utf-8');css=re.search(r'<style>(.*?)</style>',template,re.S).group(1);js=re.search(r'<script>(.*?)</script>',template,re.S).group(1)
def group(g,items):
 cards=''.join(f'<article><h3>{title}</h3><video controls muted playsinline preload="metadata" src="{name}.mp4" poster="{name}_poster.jpg"></video><p>{note}</p></article>' for name,title,note in items)
 return f'<div class="group" id="{g}" data-frames="10"><div class="controls"><button data-action="play">同步播放／暂停</button><button data-action="reset">首帧</button><button data-action="prev">上一帧</button><button data-action="next">下一帧</button><select aria-label="播放速度"><option value="1">1×</option><option value="0.5">0.5×</option><option value="0.25">0.25×</option></select><input type="range" aria-label="逐帧位置" min="0" max="9" value="0" step="1"><span class="time">0.0s</span></div><div class="videos">{cards}</div></div>'
obs=read('review_observations.json');metrics=read('metric_summary.json');state=read('state.json')
body='''<p class="small"><a href="../index.html">Hybrid总页</a> / <a href="../fence-writeback/index.html">上一轮：围栏与3秒时序</a></p><h1>继续拆外观问题：成像尺度与持续条件</h1><p><span class="pill">scene_0255</span><span class="pill">r23–r24</span><span class="pill">冻结已有DriveEditor</span></p><div class="note"><strong>用户优选的r18与r21围栏局部改善继续保留。</strong>本页把诊断正控制和实际DELETE分开；不凭局部误差下降宣布补景完成。新结果人工评价仍空。</div>
<section><h2>这轮拆哪一步</h2><div class="diagram"><svg viewBox="0 0 1140 280" role="img" aria-label="固定原图参考和模型，分别检查局部尺度和逐帧外观条件，再在原尺度逐帧审核"><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#86c4e8"/></marker></defs><g fill="#193b55" stroke="#6789a2"><rect x="10" y="97" width="185" height="78" rx="10"/><rect x="250" y="26" width="290" height="82" rx="10"/><rect x="250" y="171" width="290" height="82" rx="10"/><rect x="600" y="97" width="225" height="78" rx="10"/><rect x="885" y="97" width="240" height="78" rx="10"/></g><g text-anchor="middle" fill="#e6f4ff" font-size="18"><text x="102" y="126">原RGB / GT / 参考</text><text x="102" y="155">模型权重保持冻结</text><text x="395" y="56">r23：可见正控制</text><text x="395" y="84">相同条件裁剪 → 物体2倍大</text><text x="395" y="201">r24：实际DELETE</text><text x="395" y="230">首帧锚点 → 逐帧外观锚点</text><text x="712" y="126">已有DriveEditor</text><text x="712" y="155">两项控制依次执行</text><text x="1005" y="126">原尺度 / 全时序对照</text><text x="1005" y="155">原生与保护写回分开</text></g><g fill="none" stroke="#86c4e8" stroke-width="2" marker-end="url(#arrow)"><path d="M195 120H218V67H245"/><path d="M195 154H218V213H245"/><path d="M540 67H565V120H595"/><path d="M540 213H565V154H595"/><path d="M825 136H880"/></g></svg></div><p>r23先检查“车在视频网格中太小”是否限制细节；它没有通过完整时序身份重建。r24回到r18原设置，只检查同一外观先验在后续帧继续输入的作用。两项不叠加，便于定位。</p></section>
<section><h2>r23：先重建本来就看得见的邻车52</h2><div class="note warn">f130–139，CAM3，1秒。这里没有删除actor25；这是有真实原图可核对的重建正控制，不能当早期DELETE结果。</div><p>同r16官方零位移条件，裁剪[488,216,512,288]再放大到1024×576，使对象宽高2倍、像素面积4倍。下方三栏用相同局部显示尺寸，避免把放大显示本身当进步。</p>'''
body+=group('crop',[('original_crop','原视频 · 可见真值','真实车身和前脸供对照；后段有行人/杆件挡住车辆。'),('old_crop','r16 · 整帧推理后裁剪','旧模型结果放大到同一显示尺度。'),('new_crop','r23 · 裁剪后推理','相同参考、同seed42/25步；没有新模型或新增事实像素。')])
body+='<p class="note warn">'+html.escape(obs['r23'])+'</p><p>'+html.escape(obs['metric'])+'</p><p>'+html.escape(obs['scope'])+'</p><details open><summary>f130–134逐帧对照</summary><img src="all10_part1.jpg" alt="前五帧原图、r16和r23同尺度对照"></details><details><summary>f135–139：后段遮挡与变形</summary><img loading="lazy" src="all10_part2.jpg" alt="后五帧原图、r16和r23同尺度对照"></details></section>'
body+='<section><h2>回到原图尺度再比较</h2>'+group('full',[('original','原视频','未经生成的实际RGB。'),('old_full','旧整帧结果 · 相同mask写回','为公平比较，这里也仅写回原模型mask，外部保留原图。'),('new_full','局部推理结果 · 缩回后写回','同一mask与原尺度，避免只看放大图。')])+group('condition',[('condition','实际输入条件','只有第0帧提供原车外观；之后目标框遮掉。')])+f'<p class="small">单次新推理 {state["seconds"]:.1f}s，峰值已分配显存 {state["peak_allocated_gib"]:.2f}GiB。<a href="condition_validation.json">旧输入一致与变换检查</a> · <a href="metric_summary.json">统计口径</a> · <a href="state.json">逐帧误差</a></p></section>'
if (root/'persistent/observations.json').exists():
 v=read('persistent/observations.json');r=read('persistent/state.json')
 body+='<section id="persistent"><h2>r24：在实际DELETE中逐帧维持外观条件</h2><p>回到f65–74。删除前车25，保留真实后车52；不使用r23裁剪。第0帧条件与r18相同，后9帧新增对应SV3D315°图的RGB锚点；位置随GT52变化。其余11组条件保持相同，seed、步数、写回规则不变。这些图是生成先验，不是真实隐藏背景。</p>'+group('actual',[('../neighbor-completion/target','原视频 · DELETE25 / KEEP52','黄色是要删的前车25，青色是应保留的后车52。'),('persistent/old_final','r18 · 首帧有RGB锚点','保留用户认可的比较基线。'),('persistent/new_final','r24 · 每帧有RGB锚点','旧围栏写回保持不变，先隔离生成条件变化。')])+'<div class="note warn">'+html.escape(v['conclusion'])+'</div>'+group('native',[('persistent/old_native','r18原生生成','尚未恢复围栏和受保护原像素。'),('persistent/new_native','r24原生生成','先检查车型、轮廓、细节与背景。'),('persistent/condition','新增条件的实际序列','同一保存的SV3D视角按逐帧投影放置；可能产生平面贴图式限制，需要审核。')])+'<p>'+html.escape(v['next_step'])+'</p>'+''.join(f'<details><summary>实际DELETE第{i}组五帧对照</summary><img loading="lazy" src="persistent/all10_part{i}.jpg" alt="r18原生、r24原生和r24旧写回逐帧图"></details>' for i in [1,2])+f'<p class="small">本次推理{r["seconds"]:.1f}s，峰值显存{r["peak_allocated_gib"]:.2f}GiB。<a href="persistent/condition_validation.json">条件单变量检查</a> · <a href="persistent/observations.json">助手观察</a></p></section>'
body+='''<section><h2>第三scene：固定输入，再用同一协议检查</h2><p>沿用之前已经登记的official_000 / actor12，CAM0 f0–29。原图f0、15、29显示目标是右侧道路上的黑色MPV，尺寸随时间增加；还需保持车道线与施工护栏。当前只复核输入，没有本轮新生成。</p><details><summary>三个真实时间点与目标框</summary><img loading="lazy" src="third_scene_inputs.jpg" alt="official_000目标actor12在f0、15、29的原图"></details><p>稳定后，与0230困难例、0255遮挡邻车例一起沿用相同mask角色、参考使用规则和审核口径。三例已经参与开发，不能当作独立泛化测试；不按新生成效果挑选或更换场景。<a href="three_scene_protocol.json">完整场景与输入协议</a></p></section>
<section><h2>证据边界</h2><p>全部视频为实际10帧、10Hz，未插帧。原生生成、固定mask写回和可见正控制分别列出；没有将可见车重建的误差用于证明隐藏背景正确。r18/r21及全部旧结果保留，最终人工验收为空，仍未向Ω提供背景。无训练、下载、新模型家族、GLB/MOVE或定时任务。</p><p>本页检查静态链接、JS语法和实际视频解码；未声称浏览器交互通过。<a href="review_validation.json">验证记录</a> · <a href="review_observations.json">r23观察记录</a> · <a href="registration.json">r23登记</a></p></section>'''
(root/'index.html').write_text('<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>v77 · 外观尺度与持续条件</title><style>'+css+'</style></head><body><main>'+body+'</main><script>'+js+'</script></body></html>',encoding='utf-8',newline='\n');print('APPEARANCE_HTML_READY')
