"""实际分阶段视频审核页；所有质量判断均为助手观察，人工verdict不填写。"""
from pathlib import Path
import argparse, html, json
p=argparse.ArgumentParser();p.add_argument('directory');a=p.parse_args();root=Path(a.directory);root.mkdir(parents=True,exist_ok=True)
def video(scene,key,title,note,path=None):
 base=path or f'{scene}/{key}'
 return f'<figure><figcaption><b>{title}</b><small>{note}</small></figcaption><video controls muted playsinline preload="metadata" src="{base}.mp4" poster="{base}_poster.jpg"></video><a href="{base}.mp4">单独打开视频 ↗</a></figure>'
def group(scene,start,cards):
 return f'<div class="syncgroup" data-start="{start}"><div class="controls"><button data-act="play">同步播放</button><button data-act="pause">暂停</button><button data-act="prev">上一帧</button><button data-act="next">下一帧</button><select aria-label="播放速度"><option value="1">1×</option><option value="0.5">0.5×</option></select><output>f{start} · 0.0s</output><input type="range" min="0" max="29" step="1" value="0" aria-label="逐帧时间轴"></div><div class="grid">'+''.join(video(scene,*c) for c in cards)+'</div></div>'
style='''*{box-sizing:border-box}body{margin:0;background:#0c1320;color:#e7edf5;font:16px/1.65 system-ui,"Microsoft YaHei",sans-serif}main{max-width:1620px;padding:32px 25px 65px;margin:auto}h1{font-size:32px;line-height:1.35}h2{font-size:25px}h3{font-size:19px}a{color:#8adce8}p{max-width:1300px}small{display:block;color:#b9c8d9;font-size:13px;margin-top:5px}.notice{padding:17px 20px;border-left:4px solid #f1bb64;background:#28261e}.tag{color:#82d7eb;font-size:13px;letter-spacing:.08em}nav{display:flex;gap:24px;flex-wrap:wrap;margin:25px 0}.arch{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:25px 0}.node{flex:1;min-width:155px;background:#172a3b;border:1px solid #3d5d77;border-radius:8px;padding:13px;text-align:center}.arrow{color:#80d9ec;font-size:24px}.bad{border-color:#d27d6b;background:#37242b}section{border-top:1px solid #344356;margin-top:36px;padding-top:24px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}figure{margin:0;background:#152334;border:1px solid #32495f;border-radius:8px;overflow:hidden}figcaption{padding:12px;min-height:103px}figure>a{padding:5px 12px 10px;display:block;font-size:12px}video{width:100%;display:block;aspect-ratio:960/536;background:black}.controls{display:flex;gap:9px;align-items:center;flex-wrap:wrap;margin:18px 0 12px}button,select{font:inherit;font-size:14px;background:#223b52;border:1px solid #52718e;border-radius:6px;color:#e7edf5;padding:6px 11px;cursor:pointer}input{width:100%;accent-color:#79d1e3}output{margin-left:auto;color:#8adce8;font-variant-numeric:tabular-nums}table{border-collapse:collapse;width:100%;font-size:14px}td,th{text-align:left;vertical-align:top;border-bottom:1px solid #344356;padding:12px}th{background:#162638;color:#94d8ea}details{padding:14px;border:1px solid #344356;border-radius:8px;margin-top:16px}summary{cursor:pointer;color:#8adce8}img{max-width:100%;height:auto}code{word-break:break-all;color:#c3d9ee}footer{color:#aebed2;font-size:13px;margin-top:30px}@media(max-width:850px){main{padding:20px 14px}.grid{grid-template-columns:1fr}h1{font-size:27px}figcaption{min-height:0}}'''
parts=[f'<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>v77 · 分阶段补景定位</title><style>{style}</style></head><body><main>',
 '<div class="tag">V77 · WS-V77-HYBRID-BG-20260927 / r3–r9 · 实际结果</div><h1>把补景拆开检查：<br>车形减少了，结构和写回仍未通过</h1>',
 '<p class="notice"><b>这是继续迭代的中间检查点，目标尚未完成。</b>所有视频均为实际推理或实际中间张量，不是示意动画。两例各30帧、10Hz、3秒。模型、seed42和官方PCM 2-Step保持固定；本轮不运行Ω，不修改GLB，不执行MOVE。人眼最终 verdict 留给用户。</p>',
 '<nav><a href="#scene_0230">0230 / actor22</a><a href="#scene_0255">0255 / actor25</a><a href="#controls">控制结果</a><a href="../index.html">此前r2完整报告</a><a href="report.md">文字报告</a></nav>',
 '<div class="arch" aria-label="架构组件图">'+''.join(f'<div class="node {"bad" if "C2" in title or "D"==title[:1] else ""}"><b>{title}</b><small>{sub}</small></div>'+('<span class="arrow">→</span>' if i<5 else '') for i,(title,sub) in enumerate([('A 原视频','相机、目标和原RGB'),('B 条件遮挡','模型区域与最终写回区域分开'),('C1 像素传播','可传播内容 + 仍未填的洞'),('C2 Transformer prior','先检查这里是否已出现车形'),('D DiffuEraser','VAE初始化 → 两步去噪'),('E 保护写回','恢复邻车、围栏与真实证据')]))+'</div>',
 '<p><b>目前定位：</b>r3的C1仍有大洞，C2已补出车形；去掉prior的局部初始内容仍不能稳定去车。扩大车列条件遮挡能减少再生车辆，但会破坏场景结构。继续拆0255的D→E后，发现VAE不是主要问题，保护栏杆的mask会重新带回车轮周围像素。已做不重跑模型的写回修正，粗碎块减少，但仍有深色条带和接缝。检测为空不等于合格背景。</p>']
scenes=[('scene_0230',18,'22','CAM5','f18–47','前段灰色块状残影减轻，后段车形在局部条件下仍会再生。r6里再生车辆减少，但路灯/阴影的位置与形状不合理，画面不能通过。'),('scene_0255',65,'25','CAM3','f65–94','目标是围栏后银色SUV。r6车体形状减少，但补景出现灰色平板与接缝。围栏中央宽金属板原图就存在，应当保留；不要把它误认为再生车身。')]
for scene,start,actor,cam,window,note in scenes:
 parts+= [f'<section id="{scene}"><div class="tag">{cam} · actor{actor} · 源帧{window}</div><h2>{scene}</h2><p>{note}</p>',
  '<h3>先看全画幅：目标是谁，新结果改了什么</h3>',
  group(scene,start,[('target','① 原视频与目标','黄框只标识目标，不是生成mask。'),('r2','② 上一轮r2','保留原失败基线；有灰块/车形。',f'../{scene}/final'),('r9_full' if scene=='scene_0255' else 'r6_full','③ 最新写回控制' if scene=='scene_0255' else '③ r6逐车条件遮挡','本轮新候选；不是已通过结果。')]),
  '<h3>同一局部：r3输入修复与r6结果</h3>',
  group(scene,start,[('original_zoom','原始目标区域','三列使用完全相同的逐帧裁剪框。'),('r3','r3连贯目标矩形','替换车形mask并暂时遮住保护区；写回时仍恢复保护。'),('r6','r6逐辆遮住周围车辆','模型看不到周围车列，但最终只写目标局部。')]),
  '<h3>A→B→C：第一次车形出现在哪里</h3><p>以下为r3内部prior的实测。灰色是尚未填的规范化输入，白色剩余洞图表示未知；它们不是最终补景。原生prior为576×320，放大只用于看清阶段差别。</p>',
  group(scene,start,[('B_masked','B：已遮挡输入','先确认目标被遮住、可用上下文保留。'),('C1_propagated','C1：像素传播后','真实可搬运内容不足，中央仍有大洞。'),('C1_remaining','C1：未填洞','白色＝传播阶段未解决；不是接受的真实证据图。')]),
  group(scene,start,[('C2_transformer','C2：Transformer prior','r3车形/条带已在这里出现。'),('D_native','D：扩散原生输出','尚未做外部保护写回；与C2比较。'),('r3','E：最终保护写回','保护区原像素恢复后，仍有车形。')]),
  '<h3>只针对失败段做的控制</h3>',
  group(scene,start,[('r3_noise','r3-noise：去掉局部prior初值','同mask、模型和seed；仍会生车，prior不是唯一原因。'),('r4','r4：整块遮住周围车列','车辆减少，但杆件、路面和草地结构退化。'),('r5','r5：只替换无车prior','恢复r3局部条件；车形再次明显，不采用。')]),
  group(scene,start,[('r4_condition','r4模型所见遮挡','整块矩形会遮住车间结构；这不是最终写回范围。'),('r6_condition','r6模型所见遮挡','逐车矩形，并用GT投影约束SAM离群像素。'),('r6_prior','r6内部prior','0255草地更可辨，但最终扩散仍会改坏。')]),
  '<details><summary>四时刻静态对照与整帧视频</summary>',
  f'<p><a href="{scene}/r3_full.mp4">r3整帧</a> · <a href="{scene}/r4_full.mp4">r4整帧</a> · <a href="{scene}/r5_full.mp4">r5整帧</a> · <a href="{scene}/r6_full.mp4">r6整帧</a></p><img loading="lazy" src="{scene}/r6_quicklook.jpg" alt="原图、r4、r6 prior和r6最终结果四时刻对照"><p>四列：原图 / r4最终 / r6 prior / r6最终。所有失败和原始帧均保留。</p><a href="{scene}/r6_all30.jpg">r6全部30帧接触表</a></details>']
 if scene=='scene_0255':
  parts+=['<h3>进一步拆D：VAE → 去噪 → 写回</h3><p>r7仅增加取样钩子，重新生成的30帧与r6原生PNG最大差值为0。中间去噪状态仍含噪声，不能拿它当清晰图像质量结论。VAE保留prior布局；D原生图较连贯，最终写回才显出明显孔洞形接缝。</p>',
   group(scene,start,[('r7_vae','D0：VAE编码再解码','没有出现最终那种大块锯齿残留。'),('r7_noisy','D1：第一步后含噪latent','这是含噪内部状态，不是模型最终预测图。'),('r7_native','D2：第二步后原生输出','与r6逐像素复现；场景已被改写，仍非真实GT。')]),
   '<h3>只修E：保护mask污染与边界</h3><p>旧镂空SAM mask含原车轮附近碎块，同时漏掉部分细竖杆。r8以助手查看首帧后描出的杆线/面板替代它，沿用原LK变换；没有重跑生成模型。这是有明确人工输入的控制。粗碎块减少，但细杆边缘仍会带回原车暗色，不能叫精确抠图。</p>',
   group(scene,start,[('r8_no_static','E控制：暂不恢复静态栏杆','只用于定位碎块来源；会删除真实栏杆，不是合格编辑。'),('r8_mask','E修复输入：保护mask对照','红＝旧保护；青＝新的图像描线。'),('r8','E/r8：恢复细杆与面板','生成图完全不变；仍有细杆污染与拼接结构问题。')]),
   group(scene,start,[('r6','r6旧写回','原车周围碎块被错误保护。'),('r8','r8保护范围修正','碎块减少，仍有暗条/几何接缝。'),('r9','r9固定Poisson边界控制','仅调整边界颜色；无法修复错误结构，不准入。')]),
   '<p><a href="scene_0255/r8_full.mp4">r8全画幅</a> · <a href="scene_0255/r9_all30.jpg">r9全部30帧接触表</a></p>']
 parts.append('</section>')
parts+=['<section id="controls"><h2>相同语义guard的逐帧结果</h2><p>检测原车的正控制均为30/30。下表是“触发新车辆告警的帧数”，越小只表示告警更少；灰色马赛克、接缝和错误杆件可能完全不触发它。</p><table><tr><th>配置</th><th>0230</th><th>0255</th><th>观察与结论</th></tr>',
 '<tr><td>r2 旧Hybrid</td><td>21/30</td><td>30/30</td><td>灰块和车辆再生</td></tr><tr><td>r3 连贯矩形条件</td><td>14/30</td><td>29/30</td><td>0230早段改善，后段与0255仍失败</td></tr><tr><td>r3-noise</td><td>14/30</td><td>27/30</td><td>抹去局部prior初值不足以解决</td></tr><tr><td>r4 整块车列遮挡</td><td>2/30</td><td>0/30</td><td>有结构破坏；零检测也拒绝</td></tr><tr><td>r5 无车prior+局部条件</td><td>15/30</td><td>24/30</td><td>车形回归，不采用</td></tr><tr><td>r6 逐车条件遮挡</td><td>1/30</td><td>3/30</td><td>车形显著减少，杆件/色块/接缝仍失败</td></tr></table>',
 '<p>所有候选的指定protect与写回范围外像素变化均为0。独立检测到的邻车mask仍有约541/1,279,616、4,519–4,520/861,732像素改变，因此没有声称“所有邻车绝对不变”。r3改变了形状、范围与保护孔洞处理；r4/r6改变了条件上下文，不能把差异都归因于某个单一像素膨胀量。</p>',
 '<h3>边界与复核</h3><p>这两例已反复用于开发，不能当独立测试。GT相机/框、助手选取场景侧和围栏提示均已使用；不是纯RGB全自动。传播阶段填上18.1%/29.8%的模型孔洞不等于真实证据覆盖，原先严格接受的证据仍极少。隐藏区域没有可靠完整GT，未宣称恢复了真实世界。</p><p>任务继续集中在失败段；旧DriveEditor默认、原GLB、Ω及全部失败均保留，人工 verdict 为null。</p><p><a href="video_validation.json">远端视频实际解码</a> · <a href="review_validation.json">本地静态与解码检查</a> · <a href="summary.json">分阶段证据摘要</a></p></section>']
js='''const groups=[...document.querySelectorAll('.syncgroup')];for(const g of groups){const vs=[...g.querySelectorAll('video')],r=g.querySelector('input'),o=g.querySelector('output'),start=Number(g.dataset.start);let seeking=false;const label=()=>{const f=Math.min(29,Math.round(vs[0].currentTime*10));r.value=f;o.textContent=`f${start+f} · ${(f/10).toFixed(1)}s`};const seek=f=>{seeking=true;vs.forEach(v=>{v.pause();v.currentTime=Math.max(0,Math.min(29,f))/10});seeking=false;label()};g.querySelectorAll('button').forEach(b=>b.addEventListener('click',async()=>{const a=b.dataset.act;if(a==='play'){for(const other of groups)if(other!==g)other.querySelectorAll('video').forEach(v=>v.pause());const t=vs[0].currentTime>=2.9?0:vs[0].currentTime;vs.forEach(v=>v.currentTime=t);await Promise.allSettled(vs.map(v=>v.play()))}else if(a==='pause')vs.forEach(v=>v.pause());else seek(Number(r.value)+(a==='next'?1:-1))}));r.addEventListener('input',()=>seek(Number(r.value)));g.querySelector('select').addEventListener('change',e=>vs.forEach(v=>v.playbackRate=Number(e.target.value)));vs[0].addEventListener('timeupdate',()=>{label();if(!seeking&&!vs[0].paused)for(const v of vs.slice(1))if(Math.abs(v.currentTime-vs[0].currentTime)>.13)v.currentTime=vs[0].currentTime});vs[0].addEventListener('ended',()=>vs.forEach(v=>v.pause()))}'''
parts+=['<footer>视频逐帧实际解码、引用与JS语法检查；没有宣称浏览器交互已测试。原始PNG与日志位于远端任务目录。MP4为审核压缩版，像素合同以PNG为准。</footer>',f'<script>{js}</script></main></body></html>']
(root/'index.html').write_text('\n'.join(parts),encoding='utf-8',newline='\n')
print(root/'index.html')
