"""递归分解的实际诊断审核页，明确旧视频来源与本轮零生成边界。"""
from pathlib import Path
import argparse,json
ap=argparse.ArgumentParser();ap.add_argument('directory');root=Path(ap.parse_args().directory)
css='''*{box-sizing:border-box}body{background:#0d1621;color:#e7edf4;margin:0;font:16px/1.7 system-ui,"Microsoft YaHei",sans-serif}main{max-width:1550px;margin:auto;padding:30px 26px 65px}h1{font-size:32px;line-height:1.35}h2{font-size:25px}h3{font-size:19px}a{color:#8edce9}p{max-width:1300px}.note{background:#29271f;border-left:4px solid #ecc16c;padding:15px 20px}.tag{color:#8bcedc;font-size:13px}section{border-top:1px solid #365069;padding-top:24px;margin-top:35px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px}figure{margin:0;border:1px solid #365069;background:#142537;border-radius:8px;overflow:hidden}figcaption{padding:12px;min-height:115px}small{display:block;color:#b7c7d7;font-size:13px}video{width:100%;background:black;display:block;aspect-ratio:960/536}img{max-width:100%;height:auto}.wide{max-width:1150px}.arch{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:24px 0}.node{background:#163244;border:1px solid #47718e;border-radius:8px;padding:12px;flex:1;min-width:145px;text-align:center}.arrow{color:#90dce9;font-size:23px}table{width:100%;border-collapse:collapse;font-size:14px}th,td{border-bottom:1px solid #365069;padding:11px;text-align:left;vertical-align:top}th{background:#182d40}nav{display:flex;gap:22px;flex-wrap:wrap}.controls{display:flex;gap:10px;flex-wrap:wrap;margin:14px 0}button,select{background:#233d53;border:1px solid #4d718e;border-radius:5px;color:#e7edf4;font:inherit;padding:5px 11px;cursor:pointer}input{width:100%;accent-color:#83d6e4}output{margin-left:auto;color:#9ce0e9}details{padding:12px;border:1px solid #365069;margin:16px 0;border-radius:7px}summary{cursor:pointer;color:#9ce0e9}.split{display:grid;grid-template-columns:1fr 1fr;gap:16px}code{overflow-wrap:anywhere}footer{margin-top:35px;color:#adbdce;font-size:13px}@media(max-width:850px){main{padding:20px 14px}.grid,.split{grid-template-columns:1fr}figcaption{min-height:0}}'''
parts=[f'<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>v77 · 目标身份与证据链定位</title><style>{css}</style></head><body><main>',
 '<div class="tag">WS-V77-HYBRID-BG-20260927 · r10–r13 · 实际诊断</div><h1>先确认该保留什么，<br>再沿失败的一段继续拆</h1>',
 '<p class="note"><b>本轮尚未得到新的合格补景。</b>新完成的是原始证据审计、首帧抠图控制和两次几何证据控制。下面的 r3 / r6 视频复用已保存的生成 PNG，并新加身份标注；没有冒充新推理效果。0255 的“删除区域出现车＝幻觉”判据需要修正：目标后方确实还有其他车辆，但现有生成车形是否正确仍未验证。</p>',
 '<nav><a href="#identity">目标与邻车</a><a href="#scene_0230">0230 视频</a><a href="#scene_0255">0255 视频</a><a href="#geometry">继续拆几何</a><a href="#matte">抠图控制</a><a href="../index.html">r3–r9 分阶段旧页</a><a href="report.md">文字报告</a></nav>',
 '<div class="arch" aria-label="architecture components">'+''.join(f'<div class="node"><b>{a}</b><small>{b}</small></div>'+('<span class="arrow">→</span>' if i<5 else '') for i,(a,b) in enumerate([('A 原视频','明确只删除哪个 actor'),('B 遮挡关系','删除后什么物体会显露'),('B1 原始参考','从别的时刻/相机核对身份'),('C 真实像素投影','Ω深度 + GT相机/框 + LiDAR'),('C1 对齐与覆盖','留出验证 → 双来源 → 剩余洞'),('D 生成与写回','本轮不重跑，先检查上游前提')]))+'</div>',
 '<table><tr><th>正在拆的段</th><th>本轮发现</th><th>能否越过这一步</th></tr><tr><td>DELETE → 期望背景</td><td>0255 删除 actor25 后，actor52 等邻车可能显露；删除一个目标不等于整片区域应无车。</td><td>撤回“任意车形即新车”的强判断；不能据此通过旧结果。</td></tr><tr><td>原始参考 → 可复制像素</td><td>找到真实邻车多视角，但现有几何筛选几乎不给目标区域提供可用像素。</td><td>继续拆深度偏差和隐藏表面覆盖。</td></tr><tr><td>Ω尺度 → 对齐</td><td>局部LiDAR校正在5个视图通过留出深度检查。</td><td>仅通过稀疏深度检查；外观、遮挡与完整覆盖仍未通过。</td></tr><tr><td>对齐 → 足够背景</td><td>四查询最终仅47 / 26 / 11 / 1像素，不能补出整车或整块背景。</td><td>不放宽准入来凑覆盖，不把生成内容当真实证据。</td></tr></table>',
 '<section id="identity"><h2>0255：要删的是前排路虎，后排还有另一辆车</h2><p>左列来自原视频的 <b>actor25（删除目标）</b>；右列是 <b>actor52（需要保留的邻车）</b>，外观是另一辆银灰色 SUV。参考图来自不同时刻和相机，仍存在路牌/杆件遮挡；不是生成参考、也不是目标删除后的真值。两车不可凭“都是银色SUV”混为同一实例。</p><a href="scene_0255/actor_references/identity_reference_atlas.jpg"><img class="wide" src="scene_0255/actor_references/identity_reference_atlas.jpg" alt="左目标actor25，右邻车actor52的原视频参考"></a><p><a href="scene_0255/actor_references/references.json">每张参考的原帧、相机、GT框与选择分数</a>。框可见比例只用于挑候选，不包含全部静态遮挡。</p></section>']
for name,start,actor in [('scene_0230',18,22),('scene_0255',65,25)]:
 parts += [f'<section id="{name}"><h2>{name} · 删除 actor{actor}</h2>',
  '<p>黄框标出删除目标，青框标出 GT 射线检查中可能在目标后方显露的邻车。青框是三维包络的投影，不能证明框内任意生成车形都正确。三个视频逐帧对齐。</p>',
  f'<div class="sync" data-start="{start}"><div class="controls"><button data-act="play">同步播放</button><button data-act="pause">暂停</button><button data-act="prev">上一帧</button><button data-act="next">下一帧</button><select aria-label="速度"><option value="1">1×</option><option value="0.5">0.5×</option></select><output>f{start} · 0.0s</output><input aria-label="逐帧时间轴" type="range" min="0" max="29" step="1" value="0"></div><div class="grid">']
 for key,title,note in [('source','① 原视频与身份','黄框＝删除目标；青框＝可能被目标挡住的保留对象。'),('r3','② 既有 r3：局部生成条件','有车形和写回碎块。不能只凭检测器判断是目标残留还是邻车；形状/位置仍需核对。'),('r6','③ 既有 r6：遮住周围车列','车形减少，但邻车可能也被错误变成空地。低检测数不是更好的 DELETE 证明。')]:
  parts.append(f'<figure><figcaption><b>{title}</b><small>{note}</small></figcaption><video controls muted playsinline preload="metadata" src="{name}/{key}.mp4" poster="{name}/{key}_poster.jpg"></video></figure>')
 parts += ['</div></div>',f'<details><summary>删除后，GT框射线支持哪些物体？</summary><p>绿色＝目标原mask内，射线在目标框后还有车辆框；橙色＝没有这样的框支持。橙色也不等于已知道路，绿色不等于精确可见车身。前景围栏和完整静态几何未包含在这个诊断里。</p><video class="wide" controls muted playsinline preload="metadata" src="{name}/support.mp4" poster="{name}/support_poster.jpg"></video><p><a href="{name}/ray_support.json">30帧数值与actor ID</a> · <a href="{name}/identity_audit.jpg">原图/动态保护/静态保护检查</a> · <a href="{name}/factual_context.jpg">更大时间跨度原图</a></p></details>']
 if name=='scene_0255':parts.append('<p><b>四个原始检查帧：</b>目标SAM区域中约78.5%–83.3%的射线有后方车辆框支持，主要是 actor52。这是纠正任务判据的证据，不是给 r3 生成车形补发“正确身份”认证。r3 仍有明显模糊车体、围栏碎块；r6 的空地也缺少正确保留邻车的依据。</p>')
 else:parts.append('<p>0230 四检查帧的后方车辆框支持约6.4%–26.7%。这也需要区分邻车显露，但主体区域仍缺背景证据；此前错误杆件、阴影与车形的问题没有被本次审计修好。</p>')
 parts.append('</section>')
parts += ['<section id="geometry"><h2>把“原始参考 → 背景证据”再拆开</h2><p>r12 保留 actor52 的原始RGB和缓存Ω点，并允许它作为非目标对象的合法来源；源图中 actor25 和其他对象仍做遮挡排除。使用19个原始时刻（f65–155，间隔5帧）扫描6相机，实际留下13个视图、451个点。没有运行新的Ω，也没有用生成图反推事实。</p>',
 '<div class="arch"><div class="node">Ω深度点</div><span class="arrow">→</span><div class="node">actor52 框内</div><span class="arrow">→</span><div class="node">源图可见性</div><span class="arrow">→</span><div class="node">LiDAR 20cm 支持</div><span class="arrow">→</span><div class="node">双时刻颜色/深度一致</div><span class="arrow">→</span><div class="node">保护区排除与连续支持</div></div>',
 '<p>四个查询 r12 最终覆盖均为0。进一步检查发现：f125/CAM1 和 f135/CAM3 的稀疏LiDAR采样位置，Ω深度中位偏差分别为 −1.10m、−0.78m。采样包含静态遮挡的不确定性，不能把这些数字泛化为整个场景的 Ω 精度。</p>',
 '<details><summary>查看深度筛选中间图和原始数值</summary><img src="depth_attrition.jpg" alt="原LiDAR点与Ω框内点对照"><p><a href="depth_attrition.json">四视图逐级筛选与深度差</a></p></details>',
 '<h3>r13：仅增加一个局部尺度校正控制</h3><p>同一对象的可见LiDAR锚点按图像位置排序，交替分成拟合与留出两组；每组至少8点。只拟合一个深度比例，留出中位误差≤25cm且90分位≤50cm才使用。5个源视图通过；它们的留出中位误差从约0.80–1.35m降到0.04–0.25m。其余可见性、LiDAR距离、双来源与腐蚀阈值不变。这是有GT/LiDAR辅助的几何控制，不是模型训练，也不是全自动纯RGB重建。</p>',
 '<table><tr><th>目标帧</th><th>目标SAM像素</th><th>r12 最终支持</th><th>r13 单来源候选</th><th>r13 双来源候选</th><th>r13 最终支持</th></tr><tr><td>65</td><td>9,775</td><td>0</td><td>1,220</td><td>186</td><td>47</td></tr><tr><td>72</td><td>9,714</td><td>0</td><td>1,182</td><td>178</td><td>26</td></tr><tr><td>80</td><td>9,043</td><td>0</td><td>950</td><td>100</td><td>11</td></tr><tr><td>94</td><td>8,588</td><td>0</td><td>745</td><td>74</td><td>1</td></tr></table>',
 '<p><b>结论：</b>局部尺度偏差能修一部分，但这套严格证据链留下的区域仍不到各帧目标面积的0.5%。不能靠这些点完成背景，也不能反过来证明其他方法一定找不到隐藏表面。静态设施遮挡未完全验证，这些像素未准入后续Ω。</p>',
 '<img src="r13/neighbor_evidence_probe.jpg" alt="左原图，中既有r3，右局部校正后的稀疏真实像素，紫色是未知"><p>左：原图；中：旧r3；右：r13真实来源投影候选。<b>紫色只是未知区域标记，不是新补景效果。</b>少数支持点不足以构成可用图像。</p><p><a href="r12/summary.json">r12未校正</a> · <a href="r13/summary.json">r13校正后</a> · <a href="calibration.json">所有视图的拟合/留出结果，含拒绝视图</a></p></section>',
 '<section id="matte"><h2>E段的独立控制：首帧抠图没有解决暗边</h2><p>r11 固定 r6 生成图，只尝试 PyMatting 的 closed-form alpha 和前景颜色估计。输入是1600×900原图、助手描线的栏杆 trimap 和自动局部线位置调整；没有新增神经网络权重。下图保留实际结果。细杆暗边与锯齿仍明显，这个首帧控制停止，没有扩成30帧，也没有覆盖已有结果。</p><img src="matte_probe.jpg" alt="首帧二值保护、alpha混合和前景颜色估计对照"><p>这个失败只约束当前trimap/估计组合；不能证明所有matting无效。杆件本身也有暗面，不能把所有深色都直接归为原车污染。</p><p><a href="matte_first.json">参数与耗时</a> · <a href="centerlines.jpg">实际线位置</a> · <a href="trimap_first.png">trimap</a> · <a href="https://pymatting.github.io/alpha.html">PyMatting官方alpha接口</a> · <a href="https://pymatting.github.io/foreground.html">前景颜色估计接口</a></p></section>',
 '<section><h2>这个检查点改变了什么</h2><p>任务判据已纠正：先明确目标和保留对象，再判断车形；不再用降低车辆检测数指导整片车列消失。局部尺度校正有可复核的几何收益，但尚未形成足够的可见表面证据。后续只继续拆这一段，先区分参考视角不足、稀疏LiDAR支持和深度残差的限制，再决定如何给生成器约束。</p><p>没有新训练、生成器家族、Ω前向、GLB修改或MOVE。旧DriveEditor FULL默认和全部失败对照保留；本轮不提供可准入背景路径。人工verdict为null。</p><p><a href="video_validation.json">8个新标注视频的实际解码结果</a> · <a href="review_validation.json">本地静态引用与视频检查</a> · <a href="summary.json">证据摘要</a></p></section>']
js='''const gs=[...document.querySelectorAll('.sync')];for(const g of gs){const vs=[...g.querySelectorAll('video')],r=g.querySelector('input'),o=g.querySelector('output'),start=Number(g.dataset.start);const show=()=>{const f=Math.min(29,Math.round(vs[0].currentTime*10));r.value=f;o.textContent=`f${start+f} · ${(f/10).toFixed(1)}s`};const seek=f=>{vs.forEach(v=>{v.pause();v.currentTime=Math.max(0,Math.min(29,f))/10});show()};g.querySelectorAll('button').forEach(b=>b.onclick=async()=>{if(b.dataset.act==='play'){for(const x of gs)if(x!==g)x.querySelectorAll('video').forEach(v=>v.pause());const t=vs[0].currentTime>=2.9?0:vs[0].currentTime;vs.forEach(v=>v.currentTime=t);await Promise.allSettled(vs.map(v=>v.play()))}else if(b.dataset.act==='pause')vs.forEach(v=>v.pause());else seek(Number(r.value)+(b.dataset.act==='next'?1:-1))});r.oninput=()=>seek(Number(r.value));g.querySelector('select').onchange=e=>vs.forEach(v=>v.playbackRate=Number(e.target.value));vs[0].ontimeupdate=()=>{show();if(!vs[0].paused)for(const v of vs.slice(1))if(Math.abs(v.currentTime-vs[0].currentTime)>.13)v.currentTime=vs[0].currentTime};vs[0].onended=()=>vs.forEach(v=>v.pause())}'''
parts += [f'<script>{js}</script><footer>仅完成文件引用、JS语法、实际图像检查及视频逐帧解码；浏览器预览此前被URL安全策略拒绝，没有绕过或声称已测试浏览器交互。所有实验为开发例，隐藏真值未知。</footer></main></body></html>']
(root/'index.html').write_text('\n'.join(parts),encoding='utf-8',newline='\n');print(root/'index.html')
