"""围栏局部修复报告；原视频、旧版、新版和单因素控制均可查看。"""
from pathlib import Path
import argparse, json
p=argparse.ArgumentParser();p.add_argument('directory');root=Path(p.parse_args().directory)
def group(g,items,frames=10):
 cards=''.join(f'<article><h3>{title}</h3><video controls muted playsinline preload="metadata" src="{name}.mp4" poster="{name}_poster.jpg"></video><p>{note}</p></article>' for name,title,note in items)
 return f'<div class="group" id="{g}" data-frames="{frames}"><div class="controls"><button data-action="play">同步播放／暂停</button><button data-action="reset">首帧</button><button data-action="prev">上一帧</button><button data-action="next">下一帧</button><select aria-label="播放速度"><option value="1">1×</option><option value="0.5">0.5×</option><option value="0.25">0.25×</option></select><input type="range" aria-label="逐帧位置" min="0" max="{frames-1}" value="0" step="1"><span class="time">0.0s</span></div><div class="videos">{cards}</div></div>'
whole=group('main', [('../neighbor-completion/target','原视频 · 删25，保留52','黄框是前方目标actor25，青框是被它挡住的邻车actor52。框为GT投影包络，不是实例轮廓。'),('r18','r18 · 用户选定继续改进的版本','SUV粗形状改善；原围栏保护层带回两侧黑色碎块。'),('r21','r21 · 只替换围栏层','背景生成直接复用r18；只在登记的围栏区域重建细杆和面板。其余像素与r18完全相同。')])
local=group('local',[('old_zoom','旧写回','栏杆附近可见明显轮胎样黑块，竖杆缺失。'),('thin_zoom','控制：细mask + 原RGB','大黑块减少，但细杆上仍出现深色断线；缩mask本身不够。'),('new_zoom','修复：细杆颜色 + alpha','从原图拟合细杆前景颜色及透明度，再盖到r18背景上；不直接复制混有原车颜色的细杆像素。')])
diag=group('nofence',[('without_zoom','诊断：暂不恢复围栏','用于分离背景生成与前景写回的责任；围栏缺失，所以这段不能交付。'),('new_zoom','恢复拟合的围栏层','几何仍来自助手首帧描线和短窗LK，属于局部强控制，尚非全自动方案。')])
doc='''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>v77 · 保留r18，修复围栏写回</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{background:#0b1420;color:#e7eef6;margin:0;font:16px/1.7 system-ui,"Microsoft YaHei",sans-serif}main{max-width:1640px;margin:auto;padding:30px 24px}h1{font-size:32px;line-height:1.3}h2{font-size:24px;margin:0 0 12px}h3{font-size:17px;margin:0 0 8px}section{background:#132132;border:1px solid #2b4259;border-radius:12px;padding:24px;margin:22px 0}a{color:#95d7ff}p{margin:10px 0}.note{padding:14px 20px;background:#213747;border-left:4px solid #7bd4c1}.warn{background:#30281e;border-color:#efb36b}.small{font-size:14px;color:#b9cadd}.videos{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:15px}article{background:#0c1725;padding:12px;border-radius:8px}article p{font-size:14px}video{width:100%;aspect-ratio:16/9;background:black}.controls{display:flex;align-items:center;flex-wrap:wrap;gap:9px;margin:14px 0}button,select{background:#203d59;color:white;border:1px solid #557a9d;border-radius:6px;padding:7px 10px;cursor:pointer}input{flex:1;min-width:130px}.diagram{overflow:auto}.diagram svg{min-width:1040px;width:100%}img{max-width:100%;height:auto}details{margin:18px 0}summary{cursor:pointer;color:#95d7ff}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #345069;text-align:left}code{color:#a7d5ed}.pill{background:#233d54;border-radius:20px;padding:3px 12px;display:inline-block;margin-right:8px}@media(max-width:700px){main{padding:18px 12px}section{padding:15px}h1{font-size:26px}}
</style></head><body><main><p class="small"><a href="../index.html">Hybrid总页</a> / <a href="../neighbor-completion/index.html#repair">上一轮r18</a></p><h1>保留 r18：把围栏写回单独修好</h1><p><span class="pill">scene_0255 · CAM3</span><span class="pill">f65–74 · 1秒</span><span class="pill">r19–r21</span></p>
<div class="note"><strong>你的评价已记录：scene_0255，r18 ＞ r15，值得保留继续修。</strong><p>这一条是用户对两版的相对评价。r21尚未获人工评价；整体DELETE仍未验收。<a href="user_feedback.json">查看评价记录</a></p></div>
<section><h2>这轮改动在哪里</h2><div class="diagram"><svg viewBox="0 0 1160 215" role="img" aria-label="冻结r18背景，单独拟合围栏前景颜色与透明度，再局部合成并检查时序"><defs><marker id="a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#8dc9ee"/></marker></defs><g fill="#193b55" stroke="#66849a"><rect x="10" y="25" width="190" height="66" rx="9"/><rect x="245" y="25" width="280" height="66" rx="9"/><rect x="245" y="128" width="280" height="66" rx="9"/><rect x="585" y="67" width="255" height="86" rx="9"/><rect x="900" y="67" width="245" height="86" rx="9"/></g><g fill="#e7f4ff" text-anchor="middle" font-size="18"><text x="105" y="53">原RGB + 围栏描线</text><text x="105" y="78">不使用生成色拟合</text><text x="385" y="52">B：细杆颜色／alpha</text><text x="385" y="78">面板内部纹理</text><text x="385" y="154">A：冻结r18原生背景</text><text x="385" y="180">不重跑模型、不改车身</text><text x="712" y="99">C：只在围栏ROI合成</text><text x="712" y="126">ROI外逐像素不变</text><text x="1022" y="99">D：10帧视频与对照</text><text x="1022" y="126">候选保留，尚未准入Ω</text></g><g fill="none" stroke="#8dc9ee" stroke-width="2" marker-end="url(#a)"><path d="M200 58H240"/><path d="M525 58H550V95H580"/><path d="M525 161H550V128H580"/><path d="M840 110H895"/></g></svg></div><p>之前的保护mask把原车碎块当围栏写了回来。现在固定r18背景，分别检查“围栏几何”“细杆颜色/透明度”“最终合成”，避免把局部问题重新交给整段扩散模型。</p></section>
<section><h2>先看整幅视频</h2>'''+whole+'''<p class="note warn"><strong>助手逐帧观察：</strong>10帧中旧轮胎状黑块消失，细杆更完整。SUV车头、轮胎、反射和表面仍粗糙，右侧拼接区也有既有缺陷；这一轮没有解决它们，不能称为完美补景。</p><p class="small"><a href="r15.mp4">保留r15视频</a> · <a href="original.mp4">无遮挡标注的原视频</a> · <a href="evidence_validation.json">10帧修改范围检查</a></p></section>
<section><h2>只拆写回：大mask、细mask、前景颜色</h2>'''+local+'''<p>中栏与右栏共享新背景和细杆几何，但前景颜色来源不同。中栏直接复制原RGB，原车颜色会留在亚像素细杆上；右栏使用拟合的前景颜色与alpha重新合成，因此没有同样的黑色断线。中栏用alpha&gt;0.15的硬阈值写回，右栏是连续alpha，尚未完全分开颜色估计和软边缘各自的贡献。</p><details open><summary>逐帧放大图：f65–69</summary><a href="all10_part1.jpg"><img src="all10_part1.jpg" alt="前五帧旧写回、细mask原RGB和拟合前景对照"></a></details><details><summary>逐帧放大图：f70–74</summary><a href="all10_part2.jpg"><img loading="lazy" src="all10_part2.jpg" alt="后五帧三种围栏写回对照"></a></details>'''+diag+'''</section>
<section><h2>方法边界：这是局部显式前景控制</h2><p>首帧21段杆件中，16段从原RGB的横向亮度剖面拟合位置、宽度和颜色，5段短连接件沿用相邻材质近似。每第三个沿杆采样位置留出，留出RGB误差均值7.51，对应“不画杆”控制15.85（0–255尺度）。这只检验近似剖面模型，不能证明真实材质或整幅背景正确。</p><p>面板纹理取原图腐蚀后的内部，再延伸到边缘；几何由既有助手描线和LK传播提供。细杆尚偏平滑、暗，连接角和阴影未充分建模。不把人工描线当全自动SAM，也不把平面近似推广成整个场景的3D重建。</p><details><summary>真实源图／灰底渲染／alpha</summary><img loading="lazy" src="material_review_corrected.jpg" alt="源图、拟合围栏在纯灰背景上的渲染与透明度"></details><p class="small"><a href="alpha_first.png">首帧alpha</a> · <a href="region_first.png">允许改动范围</a> · <a href="material_fit.json">全部拟合记录</a></p><p>允许变化的围栏区域外，与r18最终图逐像素相同；模型mask外，与原视频相同。旧邻车分割与新围栏层有重叠，10帧有0–169个此类像素被前景覆盖，所以没有宣称所有邻车分割像素完全不变。它们必须按真实前后遮挡审核。</p></section>
<section><h2>先前两项几何尝试也完整保留</h2><table><thead><tr><th>尝试</th><th>看到什么</th><th>处理</th></tr></thead><tbody><tr><td>r19 自动跟踪＋三角化</td><td>300初始角点中50个落在面板；跟踪漂向草地/下杆。保留阈值下0个面板点通过三角化。</td><td>停止；没有用错位来源覆盖背景。</td></tr><tr><td>r20 人工面板四角单应</td><td>四拟合角点能对齐，但独立栏杆，特别是右侧/底部，仍有偏差。</td><td>停止；四点自拟合不当验证，没有应用RGB。</td></tr><tr><td>r21 初版合成范围错误</td><td>从原RGB而非r18最终图出发，意外修改围栏以外区域。</td><td>保留错误版本；当前视频改为从r18出发，逐帧检查ROI外0变化。</td></tr></tbody></table><details><summary>r19 跟踪证据</summary><img loading="lazy" src="tracking_review.jpg" alt="原帧跟踪点随时间漂移"></details><details><summary>r20 单应对齐证据</summary><img loading="lazy" src="alignment_review.jpg" alt="人工面板四角对齐后独立栏杆的偏差"></details><p>这两次失败只否定本次对应点/变换，不能推出原相机或Ω几何全错，也不能证明背景没有真实观测。</p></section>
<!-- TEMPORAL_EXTENSION -->
<section><h2>下一步与验收范围</h2><p>r18保留为已获用户相对好评的生成基线，r21为独立可撤销的围栏修复。先检查后续时间窗、车身细节和边界；达到相对稳定后，以同一规则加入第三个scene，保留scene_0230困难例。第三例按可见性和遮挡条件选取，不按生成结果挑“好看例子”。</p><p>每段视频都是实际10帧、10Hz，未插帧。r19–r21没有新的模型推理、权重下载、训练、Ω或GLB变动。本页静态引用、JS语法和视频实解码可检查；未声称浏览器播放交互已验证。最终背景路径仍空，人工最终验收仍空。</p><p class="small"><a href="registration.json">r21登记</a> · <a href="state.json">运行状态</a> · <a href="review_validation.json">本地验证</a> · <a href="review_observations.json">逐帧观察</a> · <a href="https://docs.opencv.org/4.13.0/d9/d0c/group__calib3d.html">OpenCV官方几何文档</a></p></section></main>
<script>document.querySelectorAll('.group').forEach(g=>{const vs=[...g.querySelectorAll('video')],m=vs[0],s=g.querySelector('input'),label=g.querySelector('.time'),n=Number(g.dataset.frames),seek=t=>{vs.forEach(v=>{v.pause();v.currentTime=t});s.value=Math.round(t*10);label.textContent=t.toFixed(1)+'s'};g.querySelector('[data-action=play]').onclick=()=>{if(m.paused)vs.forEach(v=>{v.currentTime=m.currentTime;v.play().catch(()=>{})});else vs.forEach(v=>v.pause())};g.querySelector('[data-action=reset]').onclick=()=>seek(0);g.querySelector('[data-action=prev]').onclick=()=>seek(Math.max(0,(Math.round(m.currentTime*10)-1)/10));g.querySelector('[data-action=next]').onclick=()=>seek(Math.min((n-1)/10,(Math.round(m.currentTime*10)+1)/10));s.oninput=()=>seek(Number(s.value)/10);g.querySelector('select').onchange=e=>vs.forEach(v=>v.playbackRate=Number(e.target.value));m.addEventListener('timeupdate',()=>{s.value=Math.min(n-1,Math.floor(m.currentTime*10));label.textContent=m.currentTime.toFixed(1)+'s';if(!m.paused)vs.slice(1).forEach(v=>{if(Math.abs(v.currentTime-m.currentTime)>.12)v.currentTime=m.currentTime})});m.addEventListener('ended',()=>vs.forEach(v=>v.pause()))});</script></body></html>'''
if (root/'temporal/observations.json').exists():
 obs=json.loads((root/'temporal/observations.json').read_text(encoding='utf-8-sig'))
 temporal='<section id="temporal"><h2>r22：不改参数，向后检查到3秒</h2><p>f65–74沿用r18；f75–84与f85–94新增两个独立窗口。相同参考、mask构造、seed42、25步和首帧对应SV3D锚点规则；没有跨窗帧条件。窗口边界位于1.0秒、2.0秒，需重点看车身是否跳变。</p>'+group('extension',[('temporal/original','连续原视频','f65–94，共3秒。'),('temporal/native','连续原生生成','不恢复旧围栏，先单独看车身和时序。'),('temporal/final','连续旧规则写回','为避免混淆，r22继续原r18写回；这里没有扩展r21围栏修复。')],30)+'<div class="note warn">'+obs['conclusion']+'</div><p>'+obs['next_step']+'</p><details><summary>逐时间点局部对照</summary><img loading="lazy" src="temporal/selected_frames.jpg" alt="三秒原生和写回局部对照"></details><p class="small"><a href="temporal/state.json">两窗耗时与显存</a> · <a href="temporal/condition_validation.json">条件检查</a> · <a href="temporal/observations.json">助手观察记录</a></p></section>'
 temporal+='<section><h2>窗口交界的原生图</h2><p>左列为上一窗口末帧，右列为下一窗口首帧。相机在运动，未做几何对齐，不能把全部像素差当闪烁指标；前脸、轮胎明暗与围栏残影变化仍应重点检查。</p><img src="temporal/boundaries.jpg" alt="f74/75与f84/85原生窗口交界"><details><summary>全部20个新增时间点</summary>'+''.join(f'<a href="temporal/all20_part{i}.jpg"><img loading="lazy" src="temporal/all20_part{i}.jpg" alt="新增时间窗第{i}组五帧对照"></a>' for i in range(1,5))+'</details><p class="small"><a href="temporal/compatibility_validation.json">参数化后的首窗条件与r18逐像素一致</a> · <a href="temporal/native_zoom.mp4">三秒原生局部视频</a></p></section>'
 doc=doc.replace('<!-- TEMPORAL_EXTENSION -->',temporal)
(root/'index.html').write_text(doc,encoding='utf-8',newline='\n')
print('FENCE_HTML_READY',root/'index.html')
