"""生成r14–r16本地审核页；图像结论从人工可复核观察文件读取。"""
from pathlib import Path
import argparse,json,html
p=argparse.ArgumentParser();p.add_argument('directory');a=p.parse_args();root=Path(a.directory)
read=lambda f:json.loads((root/f).read_text(encoding='utf-8-sig'))
visible=read('visible_summary.json');r15=read('state.json');r16=read('positive-control/state.json');obs=read('review_observations.json')
def esc(x):return html.escape(str(x))
def card(name,title,note):
 return f'<article><h3>{title}</h3><video controls muted playsinline preload="metadata" poster="{name}_poster.jpg" src="{name}.mp4"></video><p>{note}</p></article>'
def group(g,items):
 return f'<div class="video-group" id="{g}"><div class="controls"><button data-action="play">同步播放／暂停</button><button data-action="reset">回到首帧</button><button data-action="prev">上一帧</button><button data-action="next">下一帧</button><label>速度 <select><option value="1">1×</option><option value="0.5">0.5×</option><option value="0.25">0.25×</option></select></label><span class="time">0.0s / 1.0s</span><input aria-label="逐帧位置" type="range" min="0" max="9" value="0" step="1"></div><div class="videos">'+''.join(card(*x) for x in items)+'</div></div>'
rows=''.join(f'<tr><td>f{r["frame"]} / CAM{r["camera"]}</td><td>{r["arms"]["strict"]["coverage"]:.1%}</td><td>{r["arms"]["dense"]["coverage"]:.1%}</td><td>{r["arms"]["strict"]["median_mae"]:.1f} → {r["arms"]["dense"]["median_mae"]:.1f}</td></tr>' for r in visible['queries'])
native=group('native', [('deletion_native','空物体条件 · 原生','原生模型已生成不规则车形／暗块，后处理不是这一问题的来源。'),('neighbor_native','邻车条件 · 原生','参考是银灰SUV，输出却呈深色、低矮、拉长车身。原生错误不能用保护写回修正。')])
delete=group('delete',[('target','原视频：DELETE 25，KEEP 52','黄色框为要删的前车25；青色框为后方应保留的52。框是GT投影包络，并非精确轮廓。'),('deletion','同mask · 空物体条件','保存当前写回规则后的结果；注意围栏附近的深色碎块。'),('neighbor','同mask · 已知邻车条件','加入52原参考、3D框深度、CLIP/SV3D条件；未达到正确身份补全。')])
positive=group('positive-videos',[('positive-control/input','原视频 · 已知可见52','f130–139。这里是本来可见的车，原RGB可作对照；不是早期DELETE隐藏区域的真值。'),('positive-control/anchor','保留官方首帧贴入','官方get_editing零位移条件，包含首帧同视角车辆像素。'),('positive-control/no_anchor','只去掉首帧贴入','同参考、同3D条件、同mask、同seed；只移除首帧外观锚点。')])
conditions=group('conditions',[('positive-control/anchor_condition','输入条件 · 有首帧贴入','只有第0帧有原车外观，后9帧车辆区域遮掉。'),('positive-control/no_anchor_condition','输入条件 · 无首帧贴入','第0帧也遮掉。两个输入不是同一难度，正是要测这个差别。')])
resources=''.join(f'<tr><td>{run} / {arm}</td><td>{v["frames"]}</td><td>{v["seconds"]:.1f}s</td><td>{v["peak_allocated_gib"]:.2f}GiB</td></tr>' for run,s in [('r15',r15),('r16',r16)] for arm,v in s['arms'].items())
doc='''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>v77 · 邻车身份与首帧条件拆解</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#0b121d;color:#e1e8f2;font:16px/1.7 system-ui,"Microsoft YaHei",sans-serif}main{max-width:1640px;margin:auto;padding:32px 26px}h1{font-size:32px;line-height:1.3}h2{margin:0 0 14px;font-size:24px}h3{margin:0 0 10px;font-size:17px}p{margin:10px 0}a{color:#88cfff}section{margin:24px 0;padding:24px;background:#121f30;border:1px solid #2c3c51;border-radius:12px}.notice{padding:16px 20px;border-left:4px solid #ffb568;background:#32281e}.small{font-size:14px;color:#b4c4d6}.videos{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:16px}.videos article{padding:12px;background:#0a1422;border-radius:8px}video{width:100%;aspect-ratio:16/9;background:#070b12}article p{font-size:14px;color:#c2d0e0}.controls{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:12px 0}button,select{background:#1c3e60;border:1px solid #4b6d90;color:white;border-radius:6px;padding:7px 10px;cursor:pointer}input[type=range]{min-width:200px;flex:1}table{border-collapse:collapse;width:100%;margin:14px 0;font-size:15px}th,td{text-align:left;border-bottom:1px solid #33475e;padding:10px}.image{max-width:100%;height:auto}.ref{display:grid;grid-template-columns:240px 1fr;gap:20px;align-items:center}.ref img{width:240px;background:white;border-radius:6px}.pill{display:inline-block;background:#253851;color:#dce9f7;border-radius:20px;padding:3px 13px;margin-right:5px}.diagram{overflow:auto;background:#0b1523;border-radius:8px;padding:12px}.diagram svg{min-width:900px;width:100%;height:auto}details{margin:16px 0}summary{cursor:pointer;color:#8dcfff}.result{border-left:4px solid #eeb169;padding:8px 18px;background:#273044}.banner{border-left:4px solid #8dcfff;padding:12px 18px;background:#183148}@media(max-width:700px){main{padding:18px 12px}section{padding:15px}.ref{grid-template-columns:1fr}h1{font-size:26px}}
</style></head><body><main>
<p class="small"><a href="../index.html">Hybrid总页</a> / <a href="../stage-audit/identity-audit/index.html">上一轮：先确认后方邻车</a></p>
<h1>v77：把“补出正确邻车”继续拆开</h1><p><span class="pill">scene_0255</span><span class="pill">r14–r16</span><span class="pill">零训练 · 已有DriveEditor权重</span></p>
<div class="notice"><strong>实际DELETE仍未通过。</strong>r15的跨视角参考条件生成了错误车型，写回还恢复旧碎块。本页同时展示失败结果与更小的已知可见正控制；正控制不等于DELETE完成。人工评价保持空白。</div>
<section><h2>先看链条：这次只拆哪里</h2><div class="diagram"><svg viewBox="0 0 1200 225" role="img" aria-label="原视频和目标，真实邻车证据，条件生成，保护写回，背景准入的组件图"><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#86bfe9"/></marker></defs><g fill="#183451" stroke="#557b9c" stroke-width="1.5"><rect x="10" y="24" width="192" height="76" rx="10"/><rect x="245" y="24" width="235" height="76" rx="10"/><rect x="525" y="24" width="210" height="76" rx="10"/><rect x="778" y="24" width="190" height="76" rx="10"/><rect x="1010" y="24" width="180" height="76" rx="10"/><rect x="270" y="144" width="435" height="62" rx="10"/></g><g fill="#e5f1ff" font-family="sans-serif" text-anchor="middle" font-size="19"><text x="106" y="55">A 原RGB / 目标25</text><text x="106" y="82">确认保留邻车52</text><text x="362" y="55">B 原参考 / Ω / GT</text><text x="362" y="82">可见性与几何支持</text><text x="630" y="55">C DriveEditor</text><text x="630" y="82">外观 + 3D条件</text><text x="873" y="55">D 保护写回</text><text x="873" y="82">栏杆与邻车</text><text x="1100" y="55">候选背景</text><text x="1100" y="82">未准入Ω</text><text x="487" y="170">B1：已知可见52，同视角真实参考</text><text x="487" y="194">只比较有／无首帧车辆贴入</text></g><g fill="none" stroke="#86bfe9" stroke-width="2" marker-end="url(#arrow)"><path d="M202 62H241"/><path d="M480 62H521"/><path d="M735 62H774"/><path d="M968 62H1006"/><path d="M362 103V139"/><path d="M707 175H740V112H650V104"/></g></svg></div><p>r14检查真实点投影能否恢复已知可见车；r15检查给生成器真实邻车外观是否足够；r16把r15的困难跨视角任务缩小为同视角正控制。生成后的保护写回独立展示，避免把碎块归错环节。</p></section>
<section id="actual"><h2>r15：实际DELETE，原视频／空条件／邻车条件</h2><p>CAM3，f65–74，共1秒。删除前方actor25；actor52是后方真实存在的银灰SUV，应保留其可见部分和新显露表面。两组输入与mask完全相同。</p>'''+delete+'''
<div class="ref"><img src="reference_sv3d.png" alt="actor52用于SV3D的真实原图参考"><div><strong>这是提供给模型的actor52参考。</strong><p>原图来自f130 CAM3，以原SAM2 mask隔离，白色处不作为目标纹理。r15查询与参考相差约59°–62°；官方离散SV3D视角选315°，尚有约13.8°–17.0°量化误差。没有把不同视角crop直接粘到查询首帧。</p><p>已加入CLIP参考、SV3D视角、GT六面深度/位置，但输出仍是深色低矮车身。这否定本次适配组合的可用性，不能推出官方所有物体条件都无效。</p><a href="reference_white.png">完整参考mask</a> · <a href="azimuth_audit.json">视角记录</a> · <a href="condition_validation.json">条件检查</a></div></div>
<details><summary>全部10帧局部对照：每行原视频／空条件／邻车条件</summary><a href="all10_comparison.jpg"><img class="image" loading="lazy" src="all10_comparison.jpg" alt="r15全部十帧局部对照"></a></details></section>
<section><h2>把C→D拆开：原生生成与最终写回</h2>'''+native+'''<p>上面的两段是模型原生整帧输出，尚未恢复围栏保护层。r15原生就已有车型错误；最终视频增加的轮胎样深色碎块，则来自旧保护mask写回。原生图缺少被遮掉的真实围栏，也不能直接交付为正确背景。</p><p class="small">mask外写回像素变化为0（20帧检查），只证明写回合同，不能证明保护mask正确。<a href="masked.mp4">查看实际遮洞输入</a> · <a href="deletion_zoom.mp4">空条件局部视频</a> · <a href="neighbor_zoom.mp4">邻车条件局部视频</a></p></section>
<section id="positive"><h2>r16：先让模型重建本来就看得见的actor52</h2><div class="banner">这是同视角oracle正控制：f130–139，目标本来可见；官方零位移物体编辑接口，两组只差首帧贴入。它不提供早期DELETE隐藏区域的真实背景。</div>'''+positive+f'''<div class="result"><strong>逐帧观察：</strong><p>{esc(obs['r16_visual'])}</p><p>{esc(obs['r16_interpretation'])}</p></div>'''+conditions+'''<p>验证：第1–9帧条件完全相同；第0帧有6910个像素不同；其余11组条件完全相同。两组都带真实参考的CLIP和SV3D，以及GT六面深度。官方随机mask中心用seed42固定。</p><details><summary>查看全部10帧正控制局部图</summary><a href="positive-control/all10_comparison.jpg"><img class="image" loading="lazy" src="positive-control/all10_comparison.jpg" alt="r16全部十帧已知可见重建对照"></a></details><p class="small"><a href="positive-control/anchor_zoom.mp4">有首帧贴入局部视频</a> · <a href="positive-control/no_anchor_zoom.mp4">无首帧贴入局部视频</a> · <a href="positive-control/condition_validation.json">逐张量检查</a> · <a href="positive-control/state.json">每帧原图误差与资源</a></p></section>
<section id="geometry"><h2>r14：真实证据投影的已知可见控制</h2><p>五个原视图分别作查询，排除同一时间的全部来源。沿用已通过稀疏留出检查的局部Ω深度比例；strict保留逐点20cm LiDAR支持，dense只去掉这一项。其余SAM、GT包络、可见性、双时刻颜色/深度一致性及腐蚀相同。</p><table><thead><tr><th>查询</th><th>strict覆盖</th><th>dense覆盖</th><th>各自命中处RGB中位绝对误差</th></tr></thead><tbody>'''+rows+'''</tbody></table><p>覆盖提高仍不足；CAM1色差尤其明显，不能把稠密点直接当可靠填充。误差可能包含投影误差、曝光与视角相关反射，当前控制没有分开三者。两组误差的像素集合不同，不能作同像素精度比较。</p><details><summary>五个已知可见控制：紫色为未覆盖，右栏绿≤20／红&gt;20</summary><a href="visible_control.jpg"><img class="image" loading="lazy" src="visible_control.jpg" alt="r14已知可见投影控制"></a></details><p class="small"><a href="source_mask_review.jpg">五张原来源与SAM检查</a> · <a href="visible_summary.json">全部数字</a></p></section>
<section><h2>记录与边界</h2><p>本页所有视频都来自实际原图、条件图或模型PNG序列，10Hz、10帧、1秒，没有用插帧制造时间长度。两组r15加两组r16共40帧新生成；r14另有5张SAM2推理。无新训练、权重下载、Ω推理、GLB变更或MOVE。</p><table><thead><tr><th>控制</th><th>生成帧数</th><th>推理与保存耗时</th><th>峰值已分配显存</th></tr></thead><tbody>'''+resources+'''</tbody></table><p><strong>下一步：</strong>__NEXT_STEP__</p><p>所有结果仍为开发场景。早期隐藏表面无真值；GT框和相机、后时刻原图及助手选例均属于额外输入。已有单卡串行CFG和边界贴入修复保留；r16直接调用官方条件构造，未声称完整官方环境零改动。</p><p>旧FULL默认及全部失败保留；<code>background_input_dir=null</code>，<code>human_verdict=null</code>。静态引用、JS语法和实际视频解码验证，未声称浏览器播放交互已测试。</p><p class="small"><a href="https://github.com/yvanliang/DriveEditor">DriveEditor官方代码</a> · <a href="registration.json">r15登记</a> · <a href="positive-control/registration.json">r16登记</a> · <a href="review_validation.json">本地验证</a> · <a href="review_observations.json">观察记录</a></p></section>
</main><script>
document.querySelectorAll('.video-group').forEach(g=>{const vs=[...g.querySelectorAll('video')],master=vs[0],slider=g.querySelector('input'),label=g.querySelector('.time'),rate=g.querySelector('select');let last=-1;const seek=t=>{vs.forEach(v=>{v.pause();v.currentTime=t});slider.value=Math.round(t*10);label.textContent=t.toFixed(1)+'s / 1.0s'};g.querySelector('[data-action=play]').onclick=()=>{if(master.paused){vs.forEach(v=>{v.currentTime=master.currentTime;v.play().catch(()=>{})})}else vs.forEach(v=>v.pause())};g.querySelector('[data-action=reset]').onclick=()=>seek(0);g.querySelector('[data-action=prev]').onclick=()=>seek(Math.max(0,Math.round(master.currentTime*10-1)/10));g.querySelector('[data-action=next]').onclick=()=>seek(Math.min(.9,Math.round(master.currentTime*10+1)/10));slider.oninput=()=>seek(Number(slider.value)/10);rate.onchange=()=>vs.forEach(v=>v.playbackRate=Number(rate.value));master.addEventListener('timeupdate',()=>{label.textContent=master.currentTime.toFixed(1)+'s / 1.0s';slider.value=Math.min(9,Math.floor(master.currentTime*10));if(!master.paused)vs.slice(1).forEach(v=>{if(Math.abs(v.currentTime-master.currentTime)>.12)v.currentTime=master.currentTime})});master.addEventListener('ended',()=>vs.forEach(v=>v.pause()))});
</script></body></html>'''
replay=read('sv3d-audit/replay_validation.json');repair=read('anchor-repair/state.json')
extra='<section id="sv3d"><h2>r17：对应视角先验与视频融合分开看</h2><p>对r15邻车条件只做一次仪器化重放，10帧输出与旧结果逐像素相同；保存21个SV3D视角。选中315°视角仍呈较高车身的SUV轮廓，但车轮、背面和暗侧有模糊与形变，不能认证为准确资产。最终视频进一步变成低矮、拉长车身，说明还需检查视频融合时的外观和尺度约束。</p><div class="ref"><img src="sv3d-audit/selected_315.png" alt="实际选择的SV3D315度视角"><div><p>十帧都取view12，即相对参考315°。这张是模型生成先验，并非实拍侧面真值；未排除离散角度、尺度、特征对齐和mask上下文的贡献。</p><a href="sv3d-audit/replay_validation.json">10帧精确重放与资源记录</a></div></div><details><summary>查看全部21个实际解码视角</summary><a href="sv3d-audit/all21_views.jpg"><img class="image" loading="lazy" src="sv3d-audit/all21_views.jpg" alt="SV3D21个视角"></a></details></section>'
extra+='<section id="repair"><h2>r18：只加入对应视角的首帧锚点</h2><p>冻结r15全部条件，使用上述SV3D315°图，经现有官方贴入函数按GT52位置和比例贴入第0帧；新增8004个像素，第1–9帧不变。原CLIP／SV3D／六面深度及写回规则不变。它是生成先验再次作条件，不是真实背景证据。</p>'+group('repair-videos',[('target','原视频 · DELETE25 / KEEP52','早期实际DELETE窗口f65–74，1秒。'),('neighbor','r15 · 仅参考与3D特征条件','旧失败对照完整保留。'),('anchor-repair/final','r18 · 对应视角首帧锚点','同一秒实际新推理与原写回规则。')])+'<div class="result"><strong>实际观察：</strong><p>'+esc(obs['r18_visual'])+'</p></div>'+group('repair-native',[('anchor-repair/condition','实际模型输入','第0帧贴入来自SV3D的SUV形状；后9帧没有该RGB锚点。'),('anchor-repair/native','新模型原生输出','在写回真实围栏之前评估身份、位置和时序。')])+'<details><summary>全部10帧：旧原生／新原生／新写回</summary><a href="anchor-repair/all10_comparison.jpg"><img class="image" loading="lazy" src="anchor-repair/all10_comparison.jpg" alt="r18十帧修复对照"></a></details><p class="small"><a href="anchor-repair/zoom.mp4">新结果局部视频</a> · <a href="anchor-repair/condition_validation.json">条件检查</a> · <a href="anchor-repair/registration.json">修复登记</a> · <a href="anchor-repair/state.json">运行记录</a></p></section>'
doc=doc.replace('实际DELETE仍未通过。</strong>', '实际DELETE仍未通过。</strong>本轮删25、保留后方52；r18已改善SUV粗形状，但外观细节和写回污染仍在。').replace('<section id="geometry">',extra+'<section id="geometry">').replace('r14–r16','r14–r18').replace('两组r15加两组r16共40帧新生成','r15/r16共40帧，r18新增10帧；r17复现10帧并解码21个SV3D视角（不算新候选收益）')
doc=doc.replace('</tbody></table><p><strong>下一步',f'<tr><td>r17 / 精确重放</td><td>10 + 21视角</td><td>{replay["seconds"]:.1f}s</td><td>{replay["peak_allocated_gib"]:.2f}GiB</td></tr><tr><td>r18 / 对应视角锚点</td><td>10</td><td>{repair["seconds"]:.1f}s</td><td>{repair["peak_allocated_gib"]:.2f}GiB</td></tr></tbody></table><p><strong>下一步')
(root/'index.html').write_text(doc.replace('__NEXT_STEP__',esc(obs['next_step'])),encoding='utf-8',newline='\n');print('NEIGHBOR_HTML_READY',root/'index.html')
