"""WorldSim V6 R67：把四因子通过的 actor2 edit bake 为 transform-owned package。"""
from __future__ import annotations
import json, shutil, time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
import numpy as np
import yaml
from motion_proj.worldsim_v6.r44_verified_actor_proposal_bake import _git,_manifest_files,_resolve_runs_uri,_sha256,_verify,_write_json
from motion_proj.worldsim_v6.r46_detached_transform_package_logsim import _verify_package

TASK_ID="WS-V6-R67-TRANSFORM-OWNED-SECOND-ACTOR-BAKE-01"

def _build(output:Path, source_package:Path, source_geometry:dict[str,Any], fused:dict[str,Any], config:dict[str,Any])->tuple[dict[str,Any],float]:
    output.mkdir(parents=True,exist_ok=False); blobs=output/"blobs"; blobs.mkdir(); c=config["bake_contract"]
    arrays={}
    for name,record in source_geometry["arrays"].items():
        src=source_package/record["path"]; dst=blobs/src.name; shutil.copy2(src,dst); arrays[name]=dict(record); arrays[name]["path"]=dst.relative_to(output).as_posix()
    delta=np.asarray(c["translation_delta_m"],dtype=np.float64); transforms=np.tile(np.eye(4,dtype=np.float64),(int(c["expected_trajectory_rows"]),1,1)); transforms[:,:3,3]=delta
    temp=blobs/"proposal_transform_world.npy"; np.save(temp,transforms,allow_pickle=False); digest=_sha256(temp); transform_path=blobs/f"{digest}.npy"; temp.rename(transform_path)
    base=np.load(output/arrays["means_world_m"]["path"],allow_pickle=False).astype(np.float64); error=float(np.max(np.abs(((base+transforms[:,None,:3,3])-base)-delta[None,None,:])))
    trajectory=[{"timestamp_us":int(row["timestamp_us"]),"visible":bool(row["visible"]),"base_transform_name":row["transform_name"],"proposal_transform_index":i,"composition":"T_delta_world @ base_world_geometry"} for i,row in enumerate(source_geometry["trajectory"])]
    geometry={"schema_version":"worldsim_v6.r67_transform_owned_second_actor_package.v1","asset_id":c["asset_id"],"actor_model_index":int(c["actor_model_index"]),"chunk_id":source_geometry["chunk_id"],"proposal_id":c["proposal_id"],"package_status":c["package_status"],"primitive_count":int(source_geometry["primitive_count"]),"base_geometry_representation":"frozen_r56_actor2_world_arrays_with_lifecycle","edit_ownership":"independent_float64_world_transform_trajectory","runtime_composition_order":"T_delta_world @ base_world_geometry","translation_delta_m":delta.tolist(),"trajectory":trajectory,"base_arrays":arrays,"proposal_transform_world":{"path":transform_path.relative_to(output).as_posix(),"sha256":digest,"bytes":transform_path.stat().st_size,"dtype":transforms.dtype.str,"shape":list(transforms.shape)}}; _write_json(output/"TRAJECTORY_GEOMETRY.json",geometry)
    _write_json(output/"RUNTIME_CONTRACT.json",{"schema_version":"worldsim_v6.r67_runtime_contract.v1","asset_id":c["asset_id"],"proposal_id":c["proposal_id"],"input_base_means":arrays["means_world_m"]["path"],"input_lifecycle":arrays["actor_frame_validity"]["path"],"input_transform_trajectory":geometry["proposal_transform_world"]["path"],"equation":"p_proposal_world = T_delta_world @ p_base_world_h","lifecycle_application":"multiply_actor_opacity_by_actor_frame_validity","rotation_and_nonposition_fields":"preserve_base_byte_exact_for_pure_translation"})
    _write_json(output/"VALIDITY.json",{"schema_version":"worldsim_v6.r67_validity.v1","proposal_id":c["proposal_id"],"factor_decisions":fused["factor_decisions"],"joint_admissibility":fused["joint_admissibility"],"semantic_road":"ABSTAIN","physical_dynamics":"ABSTAIN","planning_safety":"ABSTAIN"})
    _write_json(output/"PROVENANCE.json",{"schema_version":"worldsim_v6.r67_provenance.v1","factor_fusion":{"run":config["sources"]["r66_run"],"gate_sha256":config["sources"]["r66_gate_sha256"]},"base_actor_package":{"run":config["sources"]["r56_run"],"package_manifest_sha256":config["sources"]["r56_package_manifest_sha256"]},"transformation":{"type":"constant_world_translation_float64","delta_m":delta.tolist()}})
    manifest={"schema_version":"worldsim_v6.r67_package_manifest.v1","files":_manifest_files(output)}; _write_json(output/"PACKAGE_MANIFEST.json",manifest); return manifest,error

def run_experiment(repo_root:Path,config_path:Path,run_root:Path)->Path:
    started=time.monotonic(); repo_root=repo_root.resolve()
    if _git(repo_root,"status","--porcelain"): raise RuntimeError("正式 R67 run 禁止 dirty source")
    source_commit=_git(repo_root,"rev-parse","HEAD"); config=yaml.safe_load(config_path.read_text(encoding="utf-8")); s=config["sources"]
    if config.get("task_id")!=TASK_ID: raise RuntimeError("R67 task_id 漂移")
    r66=_resolve_runs_uri(s["r66_run"]); r56=_resolve_runs_uri(s["r56_run"]); source_package=r56/"package"; geometry_path=source_package/"TRAJECTORY_GEOMETRY.json"
    frozen={r66/"MANIFEST.json":s["r66_manifest_sha256"],r66/"R66_GATE.json":s["r66_gate_sha256"],r66/"SUMMARY.json":s["r66_summary_sha256"],r66/"FUSED_EDIT_DECISION.json":s["r66_fused_decision_sha256"],r56/"MANIFEST.json":s["r56_manifest_sha256"],r56/"R56_GATE.json":s["r56_gate_sha256"],source_package/"PACKAGE_MANIFEST.json":s["r56_package_manifest_sha256"],geometry_path:s["r56_trajectory_geometry_sha256"]}
    for p,h in frozen.items(): _verify(p,h)
    source_manifest=_verify_package(source_package); source_geometry=json.loads(geometry_path.read_text(encoding="utf-8")); fused=json.loads((r66/"FUSED_EDIT_DECISION.json").read_text(encoding="utf-8")); c=config["bake_contract"]
    binding=fused["proposal_id"]==c["proposal_id"] and fused["translation_delta_m"]==c["translation_delta_m"] and fused["joint_admissibility"]=="ACCEPT_CONFORMANCE" and all(v=="ACCEPT" for v in fused["factor_decisions"].values())
    free=shutil.disk_usage(run_root).free/(1024**3)
    if free<float(config["resources"]["minimum_disk_free_gib"]): raise RuntimeError("R67 磁盘资源不足")
    run_dir=run_root/TASK_ID/f"{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}__actor2-transform-bake-s{config['seed']}-r1"; run_dir.mkdir(parents=True,exist_ok=False)
    try:
        package=run_dir/"package"; repeat=run_dir/"_repeat_package"; m1,e1=_build(package,source_package,source_geometry,fused,config); m2,e2=_build(repeat,source_package,source_geometry,fused,config); repeat_exact=m1==m2 and _sha256(package/"PACKAGE_MANIFEST.json")==_sha256(repeat/"PACKAGE_MANIFEST.json"); shutil.rmtree(repeat)
        geometry=json.loads((package/"TRAJECTORY_GEOMETRY.json").read_text(encoding="utf-8")); validity=json.loads((package/"VALIDITY.json").read_text(encoding="utf-8")); transform=geometry["proposal_transform_world"]; T=np.load(package/transform["path"],allow_pickle=False); delta=np.asarray(c["translation_delta_m"],dtype=np.float64); wall=time.monotonic()-started
        source_hashes={n:r["sha256"] for n,r in source_geometry["arrays"].items()}; baked_hashes={n:r["sha256"] for n,r in geometry["base_arrays"].items()}
        checks={"r66_and_r56_authorities_accepted":json.loads((r66/"R66_GATE.json").read_text())["checks"]["passed"] and json.loads((r56/"R56_GATE.json").read_text())["checks"]["passed"],"four_factor_proposal_binding_exact":binding,"trajectory_denominator_exact":len(geometry["trajectory"])==int(c["expected_trajectory_rows"]),"actor_primitive_denominator_exact":geometry["primitive_count"]==int(c["expected_actor_primitives"]),"all_eight_base_arrays_byte_exact_including_lifecycle":len(source_hashes)==int(c["expected_base_array_count"]) and source_hashes==baked_hashes and "actor_frame_validity" in baked_hashes,"transform_float64_content_addressed":T.dtype==np.float64 and Path(transform["path"]).stem==transform["sha256"],"transform_homogeneous_exact":np.array_equal(T[:,:3,:3],np.tile(np.eye(3),(T.shape[0],1,1))) and np.array_equal(T[:,:3,3],np.tile(delta,(T.shape[0],1))) and np.array_equal(T[:,3,:],np.tile(np.array([0.,0.,0.,1.]),(T.shape[0],1))),"transform_composition_error_exact":max(e1,e2)<=float(c["maximum_transform_composition_error_m"]),"repeat_bake_byte_exact":repeat_exact,"typed_validity_preserved":validity["joint_admissibility"]=="ACCEPT_CONFORMANCE" and all(v=="ACCEPT" for v in validity["factor_decisions"].values()),"unsupported_claims_abstain":validity["semantic_road"]==validity["physical_dynamics"]==validity["planning_safety"]=="ABSTAIN","source_immutable":all(_sha256(p)==h for p,h in frozen.items()) and source_manifest==_verify_package(source_package),"wall_within_budget":wall<=float(config["resources"]["maximum_wall_seconds"]),"training_not_started":True,"confirmation_not_read":True}; checks["passed"]=all(checks.values()); status="done" if checks["passed"] else "rejected"
        _write_json(run_dir/"R67_GATE.json",{"schema_version":"worldsim_v6.r67_gate.v1","checks":checks,"decision":"accept_transform_owned_second_actor_bake" if checks["passed"] else "reject_or_repair_transform_owned_second_actor_bake"}); _write_json(run_dir/"RESOURCE_AUDIT.json",{"schema_version":"worldsim_v6.r67_resource_audit.v1","gpu_used":False,"wall_seconds":wall,"disk_free_gib_at_start":free,"training_started":False,"confirmation_content_read":False}); _write_json(run_dir/"SUMMARY.json",{"schema_version":"worldsim_v6.r67_summary.v1","task_id":TASK_ID,"hypothesis_id":config["hypothesis_id"],"status":status,"hypothesis_outcome":"accepted_development_transform_owned_second_actor_bake" if checks["passed"] else "rejected","source_commit":source_commit,"proposal_id":c["proposal_id"],"translation_delta_m":c["translation_delta_m"],"package_manifest_sha256":_sha256(package/"PACKAGE_MANIFEST.json"),"trajectory_geometry_sha256":_sha256(package/"TRAJECTORY_GEOMETRY.json"),"runtime_contract_sha256":_sha256(package/"RUNTIME_CONTRACT.json"),"validity_sha256":_sha256(package/"VALIDITY.json"),"transform_composition_max_error_m":e1,"repeat_bake_byte_exact":repeat_exact,"claim_boundary":config["claim_boundary"]})
        tracked=["R67_GATE.json","SUMMARY.json","RESOURCE_AUDIT.json"]; _write_json(run_dir/"MANIFEST.json",{"schema_version":"worldsim_v6.r67_manifest.v1","files":{n:{"bytes":(run_dir/n).stat().st_size,"sha256":_sha256(run_dir/n)} for n in tracked},"package_manifest":{"path":"package/PACKAGE_MANIFEST.json","sha256":_sha256(package/"PACKAGE_MANIFEST.json")}}); _write_json(run_dir/"TERMINAL.json",{"schema_version":"worldsim_v6.terminal.v1","status":status,"manifest_sha256":_sha256(run_dir/"MANIFEST.json"),"summary_sha256":_sha256(run_dir/"SUMMARY.json")}); print(run_dir,flush=True); return run_dir
    except Exception as e:
        _write_json(run_dir/"TERMINAL.json",{"schema_version":"worldsim_v6.terminal.v1","status":"failed","error_type":type(e).__name__,"error":str(e)}); raise

def main()->int:
    import argparse
    p=argparse.ArgumentParser(description=__doc__); p.add_argument("--repo-root",type=Path,default=Path.cwd()); p.add_argument("--config",type=Path,default=Path("configs/worldsim_v6/r67_transform_owned_second_actor_bake_v1.yaml")); p.add_argument("--run-root",type=Path,default=Path("/root/autodl-tmp/runs/worldsim_v6")); a=p.parse_args(); run_experiment(a.repo_root,a.config,a.run_root); return 0
if __name__=="__main__": raise SystemExit(main())
