"""Distill a risk-tolerance surface from additive conformal residuals."""

from __future__ import annotations
import argparse,json,resource,time
from datetime import datetime,timezone
from pathlib import Path
import numpy as np
import torch
import torch.nn.functional as F
import yaml
from scripts.run_worldsim_v67_p109_directional_actor_uncertainty import DirectionalActorGaussian
from scripts.run_worldsim_v67_p199_joint_horizon_reliability_copula import JointHorizonCopula,_load_density
from scripts.run_worldsim_v67_p203_monotone_beta_joint_calibration import MonotoneBetaCalibration
from scripts.run_worldsim_v67_p246_extended_budget_rate_spline import MonotoneRateSplineSurface,_paired_dataset
from scripts.run_worldsim_v67_p275_epistemic_lcb_surface import _ensemble
from scripts.run_worldsim_v67_p283_conformalized_epistemic_lcb_surface import ConformalizedLCBSurface,_multipliers


def _evaluate(model,feature,mean,truth,budgets,tolerances,offsets,budget_mean,budget_scale,tol_domain,chunk):
 candidate=[]
 with torch.no_grad():
  for delta in tolerances:
   by_budget=[]
   for budget in budgets:
    values=[]
    for start in range(0,len(feature),chunk):
     x=torch.from_numpy(feature[start:start+chunk]).cuda();bz=torch.full((len(x),),(np.log(float(budget))-budget_mean)/budget_scale,device='cuda');tz=torch.full((len(x),),2*(float(delta)-tol_domain[0])/(tol_domain[1]-tol_domain[0])-1,device='cuda');values.append(model(x,bz,tz).cpu().numpy())
    by_budget.append(np.concatenate(values))
   candidate.append(np.stack(by_budget,2))
 candidate=np.stack(candidate,1);target=np.stack([np.clip(mean-float(offset),0,1) for offset in offsets],1);coverage=np.asarray([np.mean(np.all(candidate[:,i]<=truth+1e-7,axis=1)) for i in range(len(tolerances))]);desired=1-np.asarray(tolerances);return {'trajectory_count':int(len(feature)),'risk_tolerances':[float(v) for v in tolerances],'frozen_calibration_offsets':[float(v) for v in offsets],'surface_conformal_teacher_probability_MAE':float(np.mean(np.abs(candidate-target))),'final_curve_conformal_teacher_probability_MAE':float(np.mean(np.abs(candidate[:,:,-1]-target[:,:,-1]))),'simultaneous_horizon_empirical_coverages':[float(v) for v in coverage],'desired_coverages':[float(v) for v in desired],'maximum_simultaneous_horizon_undercoverage':float(np.max(np.maximum(desired-coverage,0))),'mean_conservatism_vs_teacher':float(np.mean(truth[:,None]-candidate)),'budget_monotonicity_violations':int(np.sum(np.diff(candidate,axis=3)<-1e-7)),'horizon_monotonicity_violations':int(np.sum(np.diff(candidate,axis=2)>1e-7)),'tolerance_monotonicity_violations':int(np.sum(np.diff(candidate,axis=1)<-1e-7))}


def main():
 p=argparse.ArgumentParser();p.add_argument('--config',type=Path,required=True);p.add_argument('--runs-root',type=Path,required=True);p.add_argument('--run-id',required=True);a=p.parse_args();c=yaml.safe_load(a.config.read_text());d=a.runs_root/'worldsim_v67'/c['task_id']/a.run_id;d.mkdir(parents=True,exist_ok=False);(d/'resolved.yaml').write_text(yaml.safe_dump(c,sort_keys=False));started=time.monotonic();seed=int(c['seed']);torch.manual_seed(seed);torch.cuda.reset_peak_memory_stats();ens=torch.load(a.runs_root/c['frozen_p126']['run']/c['frozen_p126']['artifact'],map_location='cuda');members=[]
 for state in ens['member_state_dicts']:
  member=DirectionalActorGaussian(20,ens['hidden_dimensions']).cuda();member.load_state_dict(state);members.append(member.eval())
 density,fd=_load_density(a.runs_root/c['frozen_p182']['run']/c['frozen_p182']['artifact']);p199=torch.load(a.runs_root/c['frozen_p199']['run']/c['frozen_p199']['artifact'],map_location='cuda');copula=JointHorizonCopula(8,p199['hidden_dimensions'],4).cuda();copula.load_state_dict(p199['model_state_dict']);copula.eval();p203=torch.load(a.runs_root/c['frozen_p203']['run']/c['frozen_p203']['artifact'],map_location='cuda');calibrator=MonotoneBetaCalibration().cuda();calibrator.load_state_dict(p203['model_state_dict']);calibrator.eval();h=np.asarray(c['horizons_seconds'],np.float32);feature_anchors=np.asarray(c['feature_anchor_budgets'],np.float32);heldout_anchors=np.asarray(c['heldout_anchor_budgets'],np.float32);heldout_budgets=np.sqrt(heldout_anchors[:-1]*heldout_anchors[1:]);domain=c['training_budget_domain'];log_min=float(np.log(domain[0]));log_max=float(np.log(domain[1]));count=int(c['training_budget_count']);fractions=(np.arange(count,dtype=np.float32)+float(c['training_budget_offset']))/count;training_budgets=np.exp(log_min+fractions*(log_max-log_min)).astype(np.float32);common=(members,ens,density,fd,p199,copula,calibrator,h,float(c['boundary_state_cost']['clearance_floor_m']),int(c['teacher']['monte_carlo_samples']),seed,float(c['teacher']['ignored_future_marginal_probability']));sf,st,_,_,_,scenes,_=_paired_dataset(a.runs_root/c['source_rows']['run']/c['source_rows']['artifact'],common,feature_anchors,training_budgets,heldout_budgets);f201,_,_,ht201,_,_,_=_paired_dataset(a.runs_root/c['p201_rows']['run']/c['p201_rows']['artifact'],common,feature_anchors,training_budgets,heldout_budgets);fresh,_,_,fresh_teacher,_,_,_=_paired_dataset(a.runs_root/c['fresh_rows']['run']/c['fresh_rows']['artifact'],common,feature_anchors,training_budgets,heldout_budgets);artifact=torch.load(a.runs_root/c['frozen_p274']['run']/c['frozen_p274']['artifact'],map_location='cuda');models=[]
 for state in artifact['member_state_dicts']:
  member=MonotoneRateSplineSurface(int(artifact['context_width']),int(artifact['rate_knot_count'])).cuda();member.load_state_dict(state);models.append(member.eval())
 budget_mean=float(artifact['budget_log_mean']);budget_scale=float(artifact['budget_log_scale']);chunk=int(c['inference_chunk_size']);source_mean,_=_ensemble(models,sf,training_budgets,budget_mean,budget_scale,chunk);p201_mean,_=_ensemble(models,f201,heldout_budgets,budget_mean,budget_scale,chunk);fresh_mean,_=_ensemble(models,fresh,heldout_budgets,budget_mean,budget_scale,chunk);cal=scenes%int(c['split']['calibration_scene_modulus'])==int(c['split']['calibration_scene_remainder']);scores=np.max(source_mean[cal]-st[cal],axis=1);tolerances=np.asarray(c['training_risk_tolerances'],np.float32);heldout=np.asarray(c['heldout_risk_tolerances'],np.float32);offsets=_multipliers(scores,tolerances);heldout_offsets=_multipliers(scores,heldout);target=np.stack([np.clip(source_mean-float(q),0,1) for q in offsets],1).astype(np.float32);train_idx=torch.from_numpy(np.flatnonzero(~cal)).cuda();x=torch.from_numpy(sf).cuda();y=torch.from_numpy(target).cuda();budget_z=torch.from_numpy(((np.log(training_budgets)-budget_mean)/budget_scale).astype(np.float32)).cuda();td=np.asarray(c['risk_tolerance_domain'],np.float32);tol_z=torch.from_numpy((2*(tolerances-td[0])/(td[1]-td[0])-1).astype(np.float32)).cuda();m=c['student'];model=ConformalizedLCBSurface(int(m['context_width']),int(m['budget_rate_knot_count']),int(m['tolerance_rate_knot_count'])).cuda();opt=torch.optim.AdamW(model.parameters(),lr=float(m['learning_rate']),weight_decay=float(m['weight_decay']));last=0.
 for step in range(int(m['steps'])):
  idx=train_idx[torch.randint(len(train_idx),(int(m['batch_size']),),device='cuda')];bi=torch.randint(len(training_budgets),(len(idx),),device='cuda');di=torch.randint(len(tolerances),(len(idx),),device='cuda');loss=F.l1_loss(model(x[idx],budget_z[bi],tol_z[di]),y[idx,di,:,bi]);opt.zero_grad(set_to_none=True);loss.backward();opt.step();last=float(loss.detach())
  if step%500==0:print(f'P284 additive conformal LCB step={step+1} mae={last:.7f}',flush=True)
 p201=_evaluate(model,f201,p201_mean,ht201,heldout_budgets,heldout,heldout_offsets,budget_mean,budget_scale,td,chunk);fresh_result=_evaluate(model,fresh,fresh_mean,fresh_teacher,heldout_budgets,heldout,heldout_offsets,budget_mean,budget_scale,td,chunk);decision=c['decision'];checks={'P201_additive_conformal_surface_fidelity':p201['surface_conformal_teacher_probability_MAE']<=float(decision['maximum_P201_surface_conformal_teacher_MAE']),'P201_empirical_simultaneous_horizon_coverage':p201['maximum_simultaneous_horizon_undercoverage']<=float(decision['maximum_P201_simultaneous_horizon_undercoverage'])};verdict=c['verdict_on_pass'] if all(checks.values()) else c['verdict_on_failure'];torch.save({'model_state_dict':model.state_dict(),'context_width':m['context_width'],'budget_rate_knot_count':m['budget_rate_knot_count'],'tolerance_rate_knot_count':m['tolerance_rate_knot_count'],'budget_log_mean':budget_mean,'budget_log_scale':budget_scale,'risk_tolerance_domain':td,'calibration_offsets':offsets,'base_model':c['frozen_p274']},d/c['model_artifact']);summary={'schema_version':c['output_schema_version'],'task_id':c['task_id'],'hypothesis_id':c['hypothesis_id'],'status':'done','verdict':verdict,'role':c['role'],'calibration':{'trajectory_count':int(cal.sum()),'score_count':int(scores.size),'training_risk_tolerances':tolerances.tolist(),'training_offsets':offsets.tolist(),'heldout_risk_tolerances':heldout.tolist(),'heldout_offsets':heldout_offsets.tolist()},'training':{'trajectory_count':int((~cal).sum()),'final_teacher_MAE':last},'P201_post_hoc_development':p201,'P243_consumed_descriptive':fresh_result,'decision_checks':checks,'resources':{'gpu':torch.cuda.get_device_name(0),'peak_gpu_memory_gib':torch.cuda.max_memory_allocated()/2**30,'peak_rss_gib':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss/2**20,'wall_seconds':time.monotonic()-started},'claim_boundary':c['claim_boundary']};(d/'summary.json').write_text(json.dumps(summary,indent=2)+'\n');(d/'status.json').write_text(json.dumps({'status':'done','completed_at_utc':datetime.now(timezone.utc).isoformat()},indent=2)+'\n');print(json.dumps({'run_dir':str(d),**summary},indent=2))


if __name__=='__main__':main()
