"""Train the inverse compiler directly through the frozen P246 response."""

from __future__ import annotations
import argparse,json,resource,time
from datetime import datetime,timezone
from pathlib import Path
import numpy as np
import torch
from torch import nn
import torch.nn.functional as functional
import yaml
from scripts.run_worldsim_v67_p109_directional_actor_uncertainty import DirectionalActorGaussian
from scripts.run_worldsim_v67_p199_joint_horizon_reliability_copula import JointHorizonCopula,_load_density
from scripts.run_worldsim_v67_p203_monotone_beta_joint_calibration import MonotoneBetaCalibration
from scripts.run_worldsim_v67_p233_monotone_prefix_reliability_surface import _dataset
from scripts.run_worldsim_v67_p246_extended_budget_rate_spline import MonotoneRateSplineSurface
from scripts.run_worldsim_v67_p249_tandem_cycle_inverse_budget import InverseReliabilityBudgetCompiler,_inverse_teacher,_probability_at_horizon_budgets,_evaluate


def main():
 p=argparse.ArgumentParser();p.add_argument('--config',type=Path,required=True);p.add_argument('--runs-root',type=Path,required=True);p.add_argument('--run-id',required=True);a=p.parse_args();c=yaml.safe_load(a.config.read_text());d=a.runs_root/'worldsim_v67'/c['task_id']/a.run_id;d.mkdir(parents=True,exist_ok=False);(d/'resolved.yaml').write_text(yaml.safe_dump(c,sort_keys=False));started=time.monotonic();torch.manual_seed(int(c['seed']));torch.cuda.reset_peak_memory_stats();ens=torch.load(a.runs_root/c['frozen_p126']['run']/c['frozen_p126']['artifact'],map_location='cuda');members=[]
 for state in ens['member_state_dicts']:
  member=DirectionalActorGaussian(20,ens['hidden_dimensions']).cuda();member.load_state_dict(state);members.append(member.eval())
 density,fd=_load_density(a.runs_root/c['frozen_p182']['run']/c['frozen_p182']['artifact']);p199=torch.load(a.runs_root/c['frozen_p199']['run']/c['frozen_p199']['artifact'],map_location='cuda');copula=JointHorizonCopula(8,p199['hidden_dimensions'],4).cuda();copula.load_state_dict(p199['model_state_dict']);copula.eval();p203=torch.load(a.runs_root/c['frozen_p203']['run']/c['frozen_p203']['artifact'],map_location='cuda');calibrator=MonotoneBetaCalibration().cuda();calibrator.load_state_dict(p203['model_state_dict']);calibrator.eval();h=np.asarray(c['horizons_seconds'],np.float32);anchors=np.asarray(c['feature_anchor_budgets'],np.float32);common=(members,ens,density,fd,p199,copula,calibrator,h);tail=(float(c['boundary_state_cost']['clearance_floor_m']),int(c['teacher']['monte_carlo_samples']),int(c['seed']),float(c['teacher']['ignored_future_marginal_probability']));sf,_,_,scenes,_=_dataset(a.runs_root/c['source_rows']['run']/c['source_rows']['artifact'],*common,anchors,*tail);f183,_,_,_,_=_dataset(a.runs_root/c['p183_rows']['run']/c['p183_rows']['artifact'],*common,anchors,*tail);f201,_,_,_,_=_dataset(a.runs_root/c['p201_rows']['run']/c['p201_rows']['artifact'],*common,anchors,*tail);frozen=torch.load(a.runs_root/c['frozen_p246']['run']/c['frozen_p246']['artifact'],map_location='cuda');teacher=MonotoneRateSplineSurface(int(frozen['context_width']),int(frozen['rate_knot_count'])).cuda();teacher.load_state_dict(frozen['model_state_dict']);teacher.eval();[parameter.requires_grad_(False) for parameter in teacher.parameters()];training_levels=np.asarray(c['training_reliability_levels'],np.float32);heldout_levels=np.asarray(c['heldout_reliability_levels'],np.float32);chunk=int(c['teacher_inverse_chunk_size']);source_target=_inverse_teacher(teacher,sf,training_levels,chunk);source_target_probability=_probability_at_horizon_budgets(teacher,sf,source_target,chunk);target183=_inverse_teacher(teacher,f183,heldout_levels,chunk);target201=_inverse_teacher(teacher,f201,heldout_levels,chunk);dev=scenes%int(c['split']['development_scene_modulus'])==int(c['split']['development_scene_remainder']);source_heldout_target=_inverse_teacher(teacher,sf[dev],heldout_levels,chunk);x=torch.from_numpy(sf).cuda();target_probability=torch.from_numpy(source_target_probability).cuda();level_tensor=torch.from_numpy(training_levels).cuda();train_idx=torch.from_numpy(np.flatnonzero(~dev)).cuda();m=c['student'];student=InverseReliabilityBudgetCompiler(int(m['context_width']),int(m['rate_knot_count'])).cuda();opt=torch.optim.AdamW(student.parameters(),lr=float(m['learning_rate']),weight_decay=float(m['weight_decay']));last_cycle=0.
 for step in range(int(m['steps'])):
  idx=train_idx[torch.randint(len(train_idx),(int(m['batch_size']),),device='cuda')];level_index=torch.randint(len(training_levels),(len(idx),),device='cuda');prediction=student(x[idx],level_tensor[level_index]);candidate_probability=torch.stack([teacher(x[idx],prediction[:,horizon])[:,horizon] for horizon in range(4)],1);loss=functional.l1_loss(candidate_probability,target_probability[idx,:,level_index]);opt.zero_grad(set_to_none=True);loss.backward();opt.step();last_cycle=float(loss.detach())
  if step%500==0:print(f'P251 direct tandem step={step+1} cycle_mae={last_cycle:.7f}',flush=True)
 source=_evaluate(student,teacher,sf[dev],source_heldout_target,heldout_levels,chunk);r183=_evaluate(student,teacher,f183,target183,heldout_levels,chunk);r201=_evaluate(student,teacher,f201,target201,heldout_levels,chunk);decision=c['decision'];checks={'P201_inverse_budget_fidelity':r201['inverse_normalized_log_budget_MAE']<=float(decision['maximum_P201_inverse_normalized_log_budget_MAE']),'P201_reconstructed_probability_fidelity':r201['reconstructed_teacher_probability_MAE']<=float(decision['maximum_P201_reconstructed_teacher_probability_MAE'])};verdict=c['verdict_on_pass'] if all(checks.values()) else c['verdict_on_failure'];torch.save({'model_state_dict':student.state_dict(),'context_width':m['context_width'],'rate_knot_count':m['rate_knot_count'],'input_dimension':36,'budget_log_mean':frozen['budget_log_mean'],'budget_log_scale':frozen['budget_log_scale'],'training_reliability_levels':training_levels,'base_model':c['frozen_p246']},d/c['model_artifact']);summary={'schema_version':c['output_schema_version'],'task_id':c['task_id'],'hypothesis_id':c['hypothesis_id'],'status':'done','verdict':verdict,'role':c['role'],'training':{'trajectory_count':int((~dev).sum()),'reliability_level_count':int(len(training_levels)),'final_cycle_probability_mae':last_cycle},'heldout_reliability_levels':[float(v) for v in heldout_levels],'source_development':source,'P183_consumed_development':r183,'P201_post_hoc_development':r201,'decision_checks':checks,'resources':{'gpu':torch.cuda.get_device_name(0),'peak_gpu_memory_gib':torch.cuda.max_memory_allocated()/2**30,'peak_rss_gib':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss/2**20,'wall_seconds':time.monotonic()-started},'claim_boundary':c['claim_boundary']};(d/'summary.json').write_text(json.dumps(summary,indent=2)+'\n');(d/'status.json').write_text(json.dumps({'status':'done','completed_at_utc':datetime.now(timezone.utc).isoformat()},indent=2)+'\n');print(json.dumps({'run_dir':str(d),**summary},indent=2))


if __name__=='__main__':main()
