"""Compile attainable budgets for variable-set additive-LCB tail risk."""

from __future__ import annotations
import argparse,json,resource,time
from datetime import datetime,timezone
from pathlib import Path
import numpy as np
import torch
import torch.nn.functional as F
import yaml
from scripts.run_worldsim_v67_p109_directional_actor_uncertainty import DirectionalActorGaussian
from scripts.run_worldsim_v67_p199_joint_horizon_reliability_copula import JointHorizonCopula,_load_density
from scripts.run_worldsim_v67_p203_monotone_beta_joint_calibration import MonotoneBetaCalibration
from scripts.run_worldsim_v67_p233_monotone_prefix_reliability_surface import _dataset
from scripts.run_worldsim_v67_p256_group_budget_dual_compiler import _groups
from scripts.run_worldsim_v67_p279_epistemic_tail_cvar_allocator import EpistemicTailCVaRAllocator
from scripts.run_worldsim_v67_p280_epistemic_tail_cvar_group_dual import _target_prices
from scripts.run_worldsim_v67_p282_variable_set_epistemic_tail_cvar_dual import VariableSetCompositeDual,_evaluate,_aggregate
from scripts.run_worldsim_v67_p283_conformalized_epistemic_lcb_surface import ConformalizedLCBSurface


def main():
 p=argparse.ArgumentParser();p.add_argument('--config',type=Path,required=True);p.add_argument('--runs-root',type=Path,required=True);p.add_argument('--run-id',required=True);a=p.parse_args();c=yaml.safe_load(a.config.read_text());d=a.runs_root/'worldsim_v67'/c['task_id']/a.run_id;d.mkdir(parents=True,exist_ok=False);(d/'resolved.yaml').write_text(yaml.safe_dump(c,sort_keys=False));started=time.monotonic();torch.manual_seed(int(c['seed']));torch.cuda.reset_peak_memory_stats();ens=torch.load(a.runs_root/c['frozen_p126']['run']/c['frozen_p126']['artifact'],map_location='cuda');members=[]
 for state in ens['member_state_dicts']:
  member=DirectionalActorGaussian(20,ens['hidden_dimensions']).cuda();member.load_state_dict(state);members.append(member.eval())
 density,fd=_load_density(a.runs_root/c['frozen_p182']['run']/c['frozen_p182']['artifact']);p199=torch.load(a.runs_root/c['frozen_p199']['run']/c['frozen_p199']['artifact'],map_location='cuda');copula=JointHorizonCopula(8,p199['hidden_dimensions'],4).cuda();copula.load_state_dict(p199['model_state_dict']);copula.eval();p203=torch.load(a.runs_root/c['frozen_p203']['run']/c['frozen_p203']['artifact'],map_location='cuda');calibrator=MonotoneBetaCalibration().cuda();calibrator.load_state_dict(p203['model_state_dict']);calibrator.eval();h=np.asarray(c['horizons_seconds'],np.float32);anchors=np.asarray(c['feature_anchor_budgets'],np.float32);common=(members,ens,density,fd,p199,copula,calibrator,h);tail=(float(c['boundary_state_cost']['clearance_floor_m']),int(c['teacher']['monte_carlo_samples']),int(c['seed']),float(c['teacher']['ignored_future_marginal_probability']));sf,_,_,ss,_=_dataset(a.runs_root/c['source_rows']['run']/c['source_rows']['artifact'],*common,anchors,*tail);f201,_,_,s201,_=_dataset(a.runs_root/c['p201_rows']['run']/c['p201_rows']['artifact'],*common,anchors,*tail);surface=torch.load(a.runs_root/c['frozen_p284']['run']/c['frozen_p284']['artifact'],map_location='cuda');teacher=ConformalizedLCBSurface(int(surface['context_width']),int(surface['budget_rate_knot_count']),int(surface['tolerance_rate_knot_count'])).cuda();teacher.load_state_dict(surface['model_state_dict']);teacher.eval();artifact=torch.load(a.runs_root/c['frozen_p288']['run']/c['frozen_p288']['artifact'],map_location='cuda');policy=EpistemicTailCVaRAllocator(int(artifact['element_width']),int(artifact['context_width']),int(artifact['rate_knot_count'])).cuda();policy.load_state_dict(artifact['model_state_dict']);policy.eval();alphas=np.asarray(c['training_alpha_fairness'],np.float32);ha=np.asarray(c['heldout_alpha_fairness'],np.float32);tolerances=np.asarray(c['training_risk_tolerances'],np.float32);ht=np.asarray(c['heldout_risk_tolerances'],np.float32);td=np.asarray(artifact['risk_tolerance_domain'],np.float32);tol_z=(2*(tolerances-td[0])/(td[1]-td[0])-1).astype(np.float32);htol_z=(2*(ht-td[0])/(td[1]-td[0])-1).astype(np.float32);floors=np.asarray(c['training_final_reliability_floors'],np.float32);hf=np.asarray(c['heldout_final_reliability_floors'],np.float32);fdomain=np.asarray(artifact['floor_domain'],np.float32);floor_z=(2*(floors-fdomain[0])/(fdomain[1]-fdomain[0])-1).astype(np.float32);hfloor_z=(2*(hf-fdomain[0])/(fdomain[1]-fdomain[0])-1).astype(np.float32);tails=np.asarray(c['training_tail_masses'],np.float32);htails=np.asarray(c['heldout_tail_masses'],np.float32);fractions=np.asarray(c['training_attainable_budget_fractions'],np.float32);hfractions=np.asarray(c['heldout_attainable_budget_fractions'],np.float32);chunk=int(c['inference_chunk_size']);steps=int(c['teacher_bisection_steps']);train={}
 for size in map(int,c['training_group_sizes']):
  groups,scenes=_groups(sf,ss,size);target,_,_=_target_prices(policy,groups,alphas,tol_z,floor_z,tails,fractions,steps,chunk);dev=scenes%int(c['split']['development_scene_modulus'])==int(c['split']['development_scene_remainder']);train[size]=(torch.from_numpy(groups).cuda(),torch.from_numpy(target).cuda(),torch.from_numpy(np.flatnonzero(~dev)).cuda())
 fz=torch.from_numpy(2*fractions-1).cuda();at=torch.from_numpy(alphas).cuda();tt=torch.from_numpy(tol_z).cuda();ft=torch.from_numpy(floor_z).cuda();qt=torch.from_numpy(tails).cuda();m=c['student'];student=VariableSetCompositeDual(int(m['element_width']),int(m['context_width']),int(m['rate_knot_count'])).cuda();opt=torch.optim.AdamW(student.parameters(),lr=float(m['learning_rate']),weight_decay=float(m['weight_decay']));sizes=list(train);last=0.
 for step in range(int(m['steps'])):
  size=sizes[step%len(sizes)];x,target,index=train[size];idx=index[torch.randint(len(index),(int(m['batch_size']),),device='cuda')];ai=torch.randint(len(alphas),(len(idx),),device='cuda');ti=torch.randint(len(tolerances),(len(idx),),device='cuda');li=torch.randint(len(floors),(len(idx),),device='cuda');qi=torch.randint(len(tails),(len(idx),),device='cuda');fi=torch.randint(len(fractions),(len(idx),),device='cuda');prediction=student(x[idx],fz[fi],at[ai],tt[ti],ft[li],qt[qi]);loss=F.l1_loss(prediction,target[idx,ai,ti,li,qi,fi]);opt.zero_grad(set_to_none=True);loss.backward();opt.step();last=float(loss.detach())
  if step%500==0:print(f'P289 variable additive tail dual step={step+1} size={size} price_mae={last:.7f}',flush=True)
 mean=float(artifact['shadow_price_log_mean']);scale=float(artifact['shadow_price_log_scale']);epsilon=float(artifact['alpha_utility_epsilon']);penalty=float(artifact['tail_CVaR_shortfall_penalty']);source={};r201={}
 for size in map(int,c['heldout_group_sizes']):
  groups,scenes=_groups(sf,ss,size);dev=scenes%int(c['split']['development_scene_modulus'])==int(c['split']['development_scene_remainder']);target,low,high=_target_prices(policy,groups[dev],ha,htol_z,hfloor_z,htails,hfractions,steps,chunk);source[str(size)]=_evaluate(student,policy,teacher,groups[dev],target,low,high,ha,htol_z,hf,hfloor_z,htails,hfractions,mean,scale,epsilon,penalty,chunk);groups,_=_groups(f201,s201,size);target,low,high=_target_prices(policy,groups,ha,htol_z,hfloor_z,htails,hfractions,steps,chunk);r201[str(size)]=_evaluate(student,policy,teacher,groups,target,low,high,ha,htol_z,hf,hfloor_z,htails,hfractions,mean,scale,epsilon,penalty,chunk)
 source=_aggregate(source);r201=_aggregate(r201);decision=c['decision'];checks={'P201_variable_set_budget_constraint_fidelity':r201['attained_budget_fraction_MAE']<=float(decision['maximum_P201_attained_budget_fraction_MAE']),'P201_variable_set_additive_composite_regret':r201['mean_frozen_composite_Lagrangian_group_utility_regret']<=float(decision['maximum_P201_mean_frozen_composite_Lagrangian_regret'])};verdict=c['verdict_on_pass'] if all(checks.values()) else c['verdict_on_failure'];torch.save({'model_state_dict':student.state_dict(),'element_width':m['element_width'],'context_width':m['context_width'],'rate_knot_count':m['rate_knot_count'],'base_model':c['frozen_p288']},d/c['model_artifact']);summary={'schema_version':c['output_schema_version'],'task_id':c['task_id'],'hypothesis_id':c['hypothesis_id'],'status':'done','verdict':verdict,'role':c['role'],'training':{'group_sizes':sizes,'final_normalized_log_price_mae':last},'heldout_group_sizes':list(map(int,c['heldout_group_sizes'])),'source_development':source,'P201_post_hoc_development':r201,'decision_checks':checks,'resources':{'gpu':torch.cuda.get_device_name(0),'peak_gpu_memory_gib':torch.cuda.max_memory_allocated()/2**30,'peak_rss_gib':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss/2**20,'wall_seconds':time.monotonic()-started},'claim_boundary':c['claim_boundary']};(d/'summary.json').write_text(json.dumps(summary,indent=2)+'\n');(d/'status.json').write_text(json.dumps({'status':'done','completed_at_utc':datetime.now(timezone.utc).isoformat()},indent=2)+'\n');print(json.dumps({'run_dir':str(d),**summary},indent=2))


if __name__=='__main__':main()
