"""Fine-tune the tail-CVaR allocator across variable group cardinalities."""

from __future__ import annotations
import argparse,json,resource,time
from datetime import datetime,timezone
from pathlib import Path
import numpy as np
import torch
import torch.nn.functional as F
import yaml
from scripts.run_worldsim_v67_p109_directional_actor_uncertainty import DirectionalActorGaussian
from scripts.run_worldsim_v67_p199_joint_horizon_reliability_copula import JointHorizonCopula,_load_density
from scripts.run_worldsim_v67_p203_monotone_beta_joint_calibration import MonotoneBetaCalibration
from scripts.run_worldsim_v67_p233_monotone_prefix_reliability_surface import _dataset
from scripts.run_worldsim_v67_p246_extended_budget_rate_spline import MonotoneRateSplineSurface
from scripts.run_worldsim_v67_p256_group_budget_dual_compiler import _groups
from scripts.run_worldsim_v67_p270_tail_cvar_equivariant_allocator import TailCVaREquivariantAllocator,_grid_probability,_teacher_targets,_evaluate


def _aggregate(by_size):
 keys=('normalized_log_budget_MAE','mean_frozen_tail_CVaR_Lagrangian_utility_regret','mean_candidate_tail_CVaR_shortfall','mean_teacher_tail_CVaR_shortfall')
 return {'evaluated_group_sizes':[int(size) for size in by_size],**{key:float(np.mean([value[key] for value in by_size.values()])) for key in keys},'price_monotonicity_violations':int(sum(value['price_monotonicity_violations'] for value in by_size.values())),'floor_monotonicity_violations':int(sum(value['floor_monotonicity_violations'] for value in by_size.values())),'by_group_size':by_size}


def main():
 p=argparse.ArgumentParser();p.add_argument('--config',type=Path,required=True);p.add_argument('--runs-root',type=Path,required=True);p.add_argument('--run-id',required=True);a=p.parse_args();c=yaml.safe_load(a.config.read_text());d=a.runs_root/'worldsim_v67'/c['task_id']/a.run_id;d.mkdir(parents=True,exist_ok=False);(d/'resolved.yaml').write_text(yaml.safe_dump(c,sort_keys=False));started=time.monotonic();torch.manual_seed(int(c['seed']));torch.cuda.reset_peak_memory_stats()
 ens=torch.load(a.runs_root/c['frozen_p126']['run']/c['frozen_p126']['artifact'],map_location='cuda');members=[]
 for state in ens['member_state_dicts']:
  member=DirectionalActorGaussian(20,ens['hidden_dimensions']).cuda();member.load_state_dict(state);members.append(member.eval())
 density,fd=_load_density(a.runs_root/c['frozen_p182']['run']/c['frozen_p182']['artifact']);p199=torch.load(a.runs_root/c['frozen_p199']['run']/c['frozen_p199']['artifact'],map_location='cuda');copula=JointHorizonCopula(8,p199['hidden_dimensions'],4).cuda();copula.load_state_dict(p199['model_state_dict']);copula.eval();p203=torch.load(a.runs_root/c['frozen_p203']['run']/c['frozen_p203']['artifact'],map_location='cuda');calibrator=MonotoneBetaCalibration().cuda();calibrator.load_state_dict(p203['model_state_dict']);calibrator.eval();h=np.asarray(c['horizons_seconds'],np.float32);anchors=np.asarray(c['feature_anchor_budgets'],np.float32);common=(members,ens,density,fd,p199,copula,calibrator,h);tail=(float(c['boundary_state_cost']['clearance_floor_m']),int(c['teacher']['monte_carlo_samples']),int(c['seed']),float(c['teacher']['ignored_future_marginal_probability']));sf,_,_,ss,_=_dataset(a.runs_root/c['source_rows']['run']/c['source_rows']['artifact'],*common,anchors,*tail);f183,_,_,s183,_=_dataset(a.runs_root/c['p183_rows']['run']/c['p183_rows']['artifact'],*common,anchors,*tail);f201,_,_,s201,_=_dataset(a.runs_root/c['p201_rows']['run']/c['p201_rows']['artifact'],*common,anchors,*tail)
 frozen=torch.load(a.runs_root/c['frozen_p246']['run']/c['frozen_p246']['artifact'],map_location='cuda');teacher=MonotoneRateSplineSurface(int(frozen['context_width']),int(frozen['rate_knot_count'])).cuda();teacher.load_state_dict(frozen['model_state_dict']);teacher.eval();base=torch.load(a.runs_root/c['frozen_p270']['run']/c['frozen_p270']['artifact'],map_location='cuda');student=TailCVaREquivariantAllocator(int(base['element_width']),int(base['context_width']),int(base['rate_knot_count'])).cuda();student.load_state_dict(base['model_state_dict'])
 domain=np.asarray(c['shadow_price_domain'],np.float32);prices=np.exp(np.linspace(np.log(domain[0]),np.log(domain[1]),int(c['training_price_count']),dtype=np.float32));heldout_prices=np.sqrt(prices[:-1]*prices[1:]);mean=.5*(np.log(domain[0])+np.log(domain[1]));scale=.5*(np.log(domain[1])-np.log(domain[0]));price_z=((np.log(prices)-mean)/scale).astype(np.float32);heldout_price_z=((np.log(heldout_prices)-mean)/scale).astype(np.float32);alphas=np.asarray(c['training_alpha_fairness'],np.float32);ha=np.asarray(c['heldout_alpha_fairness'],np.float32);floors=np.asarray(c['training_final_reliability_floors'],np.float32);hf=np.asarray(c['heldout_final_reliability_floors'],np.float32);floor_domain=np.asarray(c['final_reliability_floor_domain'],np.float32);floor_z=(2*(floors-floor_domain[0])/(floor_domain[1]-floor_domain[0])-1).astype(np.float32);heldout_floor_z=(2*(hf-floor_domain[0])/(floor_domain[1]-floor_domain[0])-1).astype(np.float32);tail_masses=np.asarray(c['training_tail_masses'],np.float32);heldout_tail_masses=np.asarray(c['heldout_tail_masses'],np.float32);grid_z=np.linspace(-1,1,int(c['teacher_budget_grid_count']),dtype=np.float32);eta_grid=np.linspace(0,float(floor_domain[1]),int(c['teacher_eta_grid_count']),dtype=np.float32);epsilon=float(c['alpha_utility_epsilon']);penalty=float(c['tail_CVaR_shortfall_penalty']);chunk=int(c['teacher_chunk_size'])
 train={}
 for size in map(int,c['training_group_sizes']):
  groups,scenes=_groups(sf,ss,size);probability=_grid_probability(teacher,groups,grid_z,chunk);target=_teacher_targets(probability,alphas,floors,tail_masses,prices,grid_z,eta_grid,epsilon,penalty);dev=scenes%int(c['split']['development_scene_modulus'])==int(c['split']['development_scene_remainder']);train[size]=(torch.from_numpy(groups).cuda(),torch.from_numpy(target).cuda(),torch.from_numpy(np.flatnonzero(~dev)).cuda())
 pz=torch.from_numpy(price_z).cuda();at=torch.from_numpy(alphas).cuda();ft=torch.from_numpy(floor_z).cuda();qt=torch.from_numpy(tail_masses).cuda();m=c['student'];opt=torch.optim.AdamW(student.parameters(),lr=float(m['learning_rate']),weight_decay=float(m['weight_decay']));sizes=list(train);last=0.
 for step in range(int(m['steps'])):
  size=sizes[step%len(sizes)];x,target,index=train[size];idx=index[torch.randint(len(index),(int(m['batch_size']),),device='cuda')];ai=torch.randint(len(alphas),(len(idx),),device='cuda');li=torch.randint(len(floors),(len(idx),),device='cuda');qi=torch.randint(len(tail_masses),(len(idx),),device='cuda');pi=torch.randint(len(prices),(len(idx),),device='cuda');prediction=student(x[idx],pz[pi],at[ai],ft[li],qt[qi]);loss=F.l1_loss(prediction,target[idx,ai,li,qi,pi]);opt.zero_grad(set_to_none=True);loss.backward();opt.step();last=float(loss.detach())
  if step%500==0:print(f'P271 variable-set tail-CVaR step={step+1} size={size} budget_mae={last:.7f}',flush=True)
 source={};r183={};r201={}
 for size in map(int,c['heldout_group_sizes']):
  groups,scenes=_groups(sf,ss,size);dev=scenes%int(c['split']['development_scene_modulus'])==int(c['split']['development_scene_remainder']);target=_teacher_targets(_grid_probability(teacher,groups[dev],grid_z,chunk),ha,hf,heldout_tail_masses,heldout_prices,grid_z,eta_grid,epsilon,penalty);source[str(size)]=_evaluate(student,teacher,groups[dev],target,ha,hf,heldout_floor_z,heldout_tail_masses,heldout_prices,heldout_price_z,epsilon,penalty,chunk)
  groups,_=_groups(f183,s183,size);target=_teacher_targets(_grid_probability(teacher,groups,grid_z,chunk),ha,hf,heldout_tail_masses,heldout_prices,grid_z,eta_grid,epsilon,penalty);r183[str(size)]=_evaluate(student,teacher,groups,target,ha,hf,heldout_floor_z,heldout_tail_masses,heldout_prices,heldout_price_z,epsilon,penalty,chunk)
  groups,_=_groups(f201,s201,size);target=_teacher_targets(_grid_probability(teacher,groups,grid_z,chunk),ha,hf,heldout_tail_masses,heldout_prices,grid_z,eta_grid,epsilon,penalty);r201[str(size)]=_evaluate(student,teacher,groups,target,ha,hf,heldout_floor_z,heldout_tail_masses,heldout_prices,heldout_price_z,epsilon,penalty,chunk)
 source=_aggregate(source);r183=_aggregate(r183);r201=_aggregate(r201);decision=c['decision'];checks={'P201_variable_set_budget_allocation_fidelity':r201['normalized_log_budget_MAE']<=float(decision['maximum_P201_normalized_log_budget_MAE']),'P201_variable_set_tail_CVaR_Lagrangian_regret':r201['mean_frozen_tail_CVaR_Lagrangian_utility_regret']<=float(decision['maximum_P201_mean_frozen_tail_CVaR_Lagrangian_utility_regret'])};verdict=c['verdict_on_pass'] if all(checks.values()) else c['verdict_on_failure'];torch.save({'model_state_dict':student.state_dict(),'element_width':base['element_width'],'context_width':base['context_width'],'rate_knot_count':base['rate_knot_count'],'input_dimension_per_member':36,'shadow_price_log_mean':mean,'shadow_price_log_scale':scale,'floor_domain':floor_domain,'alpha_utility_epsilon':epsilon,'tail_CVaR_shortfall_penalty':penalty,'base_model':c['frozen_p270']},d/c['model_artifact']);summary={'schema_version':c['output_schema_version'],'task_id':c['task_id'],'hypothesis_id':c['hypothesis_id'],'status':'done','verdict':verdict,'role':c['role'],'training':{'group_sizes':sizes,'final_normalized_log_budget_mae':last},'source_development':source,'P183_consumed_development':r183,'P201_post_hoc_development':r201,'decision_checks':checks,'resources':{'gpu':torch.cuda.get_device_name(0),'peak_gpu_memory_gib':torch.cuda.max_memory_allocated()/2**30,'peak_rss_gib':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss/2**20,'wall_seconds':time.monotonic()-started},'claim_boundary':c['claim_boundary']};(d/'summary.json').write_text(json.dumps(summary,indent=2)+'\n');(d/'status.json').write_text(json.dumps({'status':'done','completed_at_utc':datetime.now(timezone.utc).isoformat()},indent=2)+'\n');print(json.dumps({'run_dir':str(d),**summary},indent=2))


if __name__=='__main__':main()
